### ISSUE TITLE
Allow user to redesignate a Tier 1 Schedule B transaction from a previous report

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1064]
Business Reason

As a user, I will be able to "Redesignate" a transaction within a previous report so that I can attribute the disbursement amount to a different election.

Acceptance Criteria

***Given*** I am viewing a ***Tier 1*** Schedule B Line 23 and 30b transaction on a previously submitted report (Submission success),

*   CONDUIT_EARMARK_OUT
*   CONTRIBUTION_TO_CANDIDATE
*   CONTRIBUTION_TO_CANDIDATE_VOID
*   FEDERAL_ELECTION_ACTIVITY_100PCT_PAYMENT
*   FEDERAL_ELECTION_ACTIVITY_CREDIT_CARD_PAYMENT
*   FEDERAL_ELECTION_ACTIVITY_PAYMENT_TO_PAYROLL
*   FEDERAL_ELECTION_ACTIVITY_STAFF_REIMBURSEMENT
*   FEDERAL_ELECTION_ACTIVITY_VOID
*   IN_KIND_CONTRIBUTION_TO_CANDIDATE
*   PAC_CONDUIT_EARMARK_OUT

       ***When*** I initiate a ‘Redesignate’ function for that transaction

       ***Then*** the system will ask me to confirm which "In progress" report of the ***same report type*** I would like to add the redesignation to, 

       ***Then*** I will be able to indicate the how much should be redesignated and to which election, as follows:

—

1.  Contact

       #

*   _(Contact will auto-pull from original contribution and cannot be edited)_

1.  Address

       #

*   _(Address will auto-pull from original contribution and cannot be edited)_

1.  Expenditure information

       #

*   ***REDESIGNATION DATE*** (Required)
*   ***MEMO ITEM*** (Required, automatically checked by the system and user cannot change it)
*   ***REDESIGNATION AMOUNT*** (Required, must be positive and cannot exceed amount of original disbursement)

1.  Committee/Candidate information

       #

*   Committee/Candidate values should match the original contribution and cannot be edited

1.  ELECTION INFORMATION

       #

*   ***ELECTION CODE*** (Required)
*   ***ELECTION YEAR*** (Required)
*   ***ELECTION DESCRIPTION*** (Required if Election Code is Other)

1.  Additional information

       #

*   ***PURPOSE OF DISBURSEMENT*** (Required, system generated) 
      *   "Redesignation - Contribution from XX", where XX = Date of Original Transaction
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (values should match the original disbursement and be read-only)

—

***And*** the system will auto-generate a transaction showing amount and election _redesignated from_ with the following information:

1.  Contact

       #

*   _(Contact will auto-pull from original disbursement)_

1.  Address

       #

*   _(Address will auto-pull from original disbursement)_

1.  Expenditure information

       #

*   ***REDESIGNATION DATE*** (required, auto-generated from "Redesignation To" transaction)
*   ***MEMO ITEM*** (required, automatically checked by the system and user cannot change it)
*   ***REDESIGNATION AMOUNT*** (required, auto-generated from "Redesignation To" transaction and _made negative_)

1.  Committee/Candidate information

       #

*   Committee/Candidate values should match the original disbursement

1.  ELECTION INFORMATION

       #

*   Election Information values should match the original disbursement

1.  Additional information

       #

*   ***PURPOSE OF RECEIPT*** (Required, system generated) 
      *   "Redesignation - Contribution from XX", where XX = Date of Original Transaction
*   ***NOTE OR MEMO TEXT*** (Optional)
*   ***CATEGORY CODE*** (values should match the original disbursement and be read-only)

—

  ***And*** the system will auto-generate a transaction with the following information:

*   **Copy of the all the details from the original transaction, with the MEMO checkbox selected.
*   ***PURPOSE OF DISBURSEMENT*** (Required, system generated) 
      *   "(Originally disclosed on XX report.) See redesignation below.", where XX will be filled in with #1454 (remain XX for now).

             —

***Then*** I will be able to:

*   Cancel
*   Edit
*   Save transactions (users must save all three at the same time)

***And*** upon saving:

*   the user will be taken to the in-progress report the redesignation has been saved on
*   all three transactions will be saved on the selected report as memo items with their original line numbers.
*   all three will be associated to the copy of the original disbursement on the current report by their back reference IDs.
*   the copy of the original transaction will be ***unaggregated.***
*   on the backend: 
      *   Copy of original transaction: REATTRIBUTION REDESIGNATION TAG set to REDESIGNATED
    *   First transaction above (Redesignated To): REATTRIBUTION REDESIGNATION TAG set to REDESIGNATION_TO
    *   Second transaction above (Redesignated From): REATTRIBUTION REDESIGNATION TAG set to REDESIGNATION_FROM

***And*** when the user opens a redesigated transaction, it will take them back to the "Redesignation From/To" entry form.

Dev Note

*   This functionality should ONLY be for Tier 1 (parent) transactions.
*   Any existing "children" of the original transaction do _not_ come over to the current report.
*   The copy of the original transaction will be ***unaggregated.***
*   This will be a **[specification overlay]([https://docs.google.com/spreadsheets/d/1AbYjbtwZNuB8Y1GHAXMwSzxJW41Pr_3J/edit#gid=1399838959)**](https://docs.google.com/spreadsheets/d/1AbYjbtwZNuB8Y1GHAXMwSzxJW41Pr_3J/edit#gid=1399838959)**), with specifications here replacing those on the original disbursement. The remaining specifications will match the original.
*   Copy of original transaction: REATTRIBUTION REDESIGNATION TAG set to REDESIGNATED
*   First transaction above (Redesignated To): REATTRIBUTION REDESIGNATION TAG set to REDESIGNATION_TO
*   Second transaction above (Redesignated From): REATTRIBUTION REDESIGNATION TAG set to REDESIGNATION_FROM

Wireframes

1.  Select Redesignation
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzEyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2bd4487c01ab997e7394e58566f5020ceb4635d2/1064%20-%20Kabob%20%E2%80%93%201.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzEyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2bd4487c01ab997e7394e58566f5020ceb4635d2/1064%20-%20Kabob%20%E2%80%93%201.png))

1.  Select report
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7cb9576c44474c236373c209c4b63fe0fce1824/624%20select.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7cb9576c44474c236373c209c4b63fe0fce1824/624%20select.png))

1.  Report selected
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aeafe298db72328f44e65c49cc4ae87f3e97a7bd/624%20-%20Allow%20user%20to%20reattribute%20a%20Tier%201%20transaction%20from%20a%20previous%20report.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aeafe298db72328f44e65c49cc4ae87f3e97a7bd/624%20-%20Allow%20user%20to%20reattribute%20a%20Tier%201%20transaction%20from%20a%20previous%20report.png))

1.  Redesignation to
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1VWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--011de6c4b133d11587aea13bcfed957ad722138c/1064%20-%20Redesignation%20to.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1VWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--011de6c4b133d11587aea13bcfed957ad722138c/1064%20-%20Redesignation%20to.png))

1.  Redesignation from
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1lWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b35ad876a4c2e559a0d5af57e49e39525bcf458/1064%20-%20Redesignation%20from.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1lWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b35ad876a4c2e559a0d5af57e49e39525bcf458/1064%20-%20Redesignation%20from.png))

1.  Copy of original transaction
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2NWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d1fd043aca58ecadae2aa55431e8ba2c9086a0a/1064%20-%20third%20transaction.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2NWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d1fd043aca58ecadae2aa55431e8ba2c9086a0a/1064%20-%20third%20transaction.png))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
- [x] BA/Design Quality Checklist complete
- This functionality should ONLY be for Tier 1 (parent) transactions.
- Any existing "children" of the original transaction do _not_ come over to the current report.
- The copy of the original transaction will be **unaggregated.**

 See full ticket and images here: [FECFILE-776](https://fecgov.atlassian.net/browse/FECFILE-776)

**Comment by MitchellTCG** [comment]
Edits made

@GreggMoreland 
please review

**Comment by AureliaKhorsand** [comment]
@MitchellTCG what does selecting the correct in-progress report look like?

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Report selection added

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Please verify the list of transactions that can be redesignated for this ticket.

The list that was struckthrough was what was originally in the acceptance criteria
the new list is what Matt says the specs say.

**Comment by GreggMoreland** [comment]
@mjtravers @WiseQA @MitchellTCG @AureliaKhorsand I have confirmed that the new list is correct.

**Comment by WiseQA** [comment]
During QA / DEV review the following need hotfixed.

1.  PURPOSE OF DISBURSEMENT (OPTIONAL) should be PURPOSE OF DISBURSEMENT (SYSTEM GENERATED).   Text should show the below text as read-only.

- "Redesignation - Contribution from XX", where XX = Date of Original Transaction

<img width="700" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0U1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--989433b86903e6a3db10521b92f81ddf85c20fca/image.png" alt="image.png" />

2.  "Change Contribution to Candidate" to "Redesignation from"
3.  Label incorrect should be PURPOSE OF DISBURSEMENT (SYSTEM GENERATED) and field read-only.

<img width="1162" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEU1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57b55aaeed550b04e957b2ff06e3737eb6418cd0/image.png" alt="image.png" />

4.   The NOTE OR MEMO TEXT (OPTIONAL) bugs (known issues) will be fixed in ticket #1414 and #1415

@MitchellTCG @mjtravers the above fixes are denoted as hotfixes.   Ticket on-hold.

**Comment by WiseQA** [comment]
During DEV / QA review, the functionality for the **"Select a report" from the dropdown for redesinate is for Form 3x reports only** (Original and future reports).   In the "Select a report" drop down when reattributing or **redesignating** a transaction from a prior submitted F3X report, the drop down is also showing all Form 1M, Form 24, Form 99, and past Form 3X reports.

<img width="1227" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cbe559ed9c1ce615b060aa2d8029b94173f5ac8/image.png" alt="image.png" />

@MitchellTCG @mjtravers Hotfix for this ticket.

**Comment by mjtravers** [comment]
Fix made for dropdown issue and labels. Deployed to STAGE.

**Comment by WiseQA** [comment]
QA testing using Login.gov on STAGE.  QA review verified Redesignation of  Disbursements (see list in AC) from previous report.  (Tested using CONTRIBUTION_TO_CANDIDATE.  e2e testing for additional transactions)

Verified "Select Redesignation"

<img width="1447" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVZIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62e68947ff9d4550285bdc519edab1c8047e43d2/image.png" alt="image.png" />

________________________________________________________________________________________________
Verified the fix was implemented for the functionality for the "Select a report" from the dropdown for redesignate is for Form 3x reports only (Original and future reports).    Then select report to redesignation.

<img width="1501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWRIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--866261de3a58d3d0d643969e8a056d85b2f6ebc7/image.png" alt="image.png" />

<img width="1492" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTVIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ae2a16719dcdb205ff6d386254442bec5ae0846/image.png" alt="image.png" />

________________________________________________________________________________________________________

Verified "Redesignation to" page is displayed.   Enter required fields.

<img width="1225" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTlIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4fed88163f9e21160abeed08aefb8b86032c5702/image.png" alt="image.png" />

__________________________________________________________________________________________

Verified "Redesignation from" page is displayed.   Enter required fields.

<img width="1385" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmRIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81044bccebd4bbcd363f811443fac9ee54664093/image.png" alt="image.png" />

____________________________________________________________________________________________________

Verify transaction has been redesignated to the correct report.

<img width="1487" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnhIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5790fe15c100f219d7f9ae442c95881f525c56cf/image.png" alt="image.png" />

Verified PURPOSE OF DISBURSMENT and NOTE OR MEMO TEXT fields populating correctly.
____________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
