### ISSUE TITLE
Fix transaction dropdowns that do not get proper value (e2e)

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1299]
The nightly e2e tests are throwing an error where the entity type dropdown is not getting the proper value.

See e2e report here: [https://output.circle-artifacts.com/output/job/73830312-860a-40e4-af15-9b9884b07561/artifacts/0/cypress/results/fail_2023-07-27T040100+0000-reports-f3x-transactions.html](https://output.circle-artifacts.com/output/job/73830312-860a-40e4-af15-9b9884b07561/artifacts/0/cypress/results/fail_2023-07-27T040100+0000-reports-f3x-transactions.html)

To reproduce the "Create a Group FG transaction" error:

  1) Create a PAC Earmark Receipt transaction

  2) Enter and Individual entity type for the STEP 2 PAC Earmark Memo

  3) After saving the double transaction open it up again from the Manager Transactions Screen

  4) See that the PAC Earmark Memo entity type dropdown is read only and a COM if created as a COM or IND if created as an IND.

To reproduce the "Create a Group E, D, A Tier 3 transactions" error:

  1) Create a new JF Transfer transaction

  2) Save JF Transfer by clicking "Save & add memo" and select "Parnership Receipt"

  3) Create a new Partnership Receipt transaction

  4) Save Partnership Receipt by clicking "Save & add memo" and select "Individual"

  4) See on the "Individual Joint Fundraising Transfer Memo" page that the entity type dropdown is read only and ORG, not IND

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-651](https://fecgov.atlassian.net/browse/FECFILE-651)

**Comment by WiseQA** [comment]
QA review just retested and verified bug is valid.   How many points for this ticket Matt ?

e2e notification of test failing showing 2 fails:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/15c1bad5-3a9a-427e-8788-4ca9f227c7d9)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/44383b2f-9086-47a4-9608-331c03dc4fca)

**Comment by mjtravers** [comment]
This patch fixes 2 issues:

When an existing contact is edited, the contact lookup drop down was not checking the existing entity_type value when setting the value of that field. It was simply using the first value of the contactTypeOptions array.

When a new memo transaction is saved with the "Save & create another" memo, the URL contains the parent ID which does not change across sibling transaction types so the URL was not changing for the new sibling transaction form and the initialization was based on the previously saved transaction. The fix was to add a new feature in the angular RouteReuseStrategy to force destroy and recreate the route component based on a custom route flag.

**Comment by mjtravers** [comment]
Passes CR. Ready for QA on DEV.

**Comment by WiseQA** [comment]
QA review verified the transaction dropdowns are getting the proper values.   The following was retested and PASSED.

Verified the "Create a Group FG transaction" error was fixed by retesting following steps:

1.  Create a PAC Earmark Receipt transaction
2.  Enter and Individual entity type for the STEP 2 PAC Earmark Memo
3.  After saving the double transaction open it up again from the Manager Transactions Screen
4.  See that the PAC Earmark Memo entity type dropdown is read only and a COM if created as a COM or IND if created as an IND.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bb80ee7a-a47d-4736-a867-06542cb8bd43)

Verified the "Create a Group E, D, A Tier 3 transactions" error was fixed by retesting following steps::

1.  Create a new JF Transfer transaction
2.  Save JF Transfer by clicking "Save & add memo" and select "Parnership Receipt"
3.  Create a new Partnership Receipt transaction
4.  Save Partnership Receipt by clicking "Save & add memo" and select "Individual"
5.  See on the "Individual Joint Fundraising Transfer Memo" page that the entity type dropdown is read only and ORG, not IND

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6e24bf69-24fe-4d65-8e8f-970b5d9a02a6)

QA Review Completed.   Defect PASSES.   Moved to Stage Ready.
