### ISSUE TITLE
Fix debt transaction issues on Loans and Debts table

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#1361]
With the recent addition of Schedule D debts to the Loans and Debts table, there are a couple of issues to fix since this is the first table the app has that contains more than one type of Schedule.

1\. Fix the ***Date Incurred*** sorting which does not factor in the values for the Schedule D debt records
[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVJ6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b0beb622a551c789277bec90ecc10265b1e01ca3/image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVJ6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b0beb622a551c789277bec90ecc10265b1e01ca3/image.png))

  2\. Fix the ***Balance*** column sorting.

***DEV Notes***

  The backend needs to be revamped so that sorting works across the transaction_schedulec and transaction_scheduled tables with different column names for the same sort. Maybe a table sql union with a column name alias to sync up the table column names?

### QA Notes ###
null

### DEV Notes ###
1. Fix the **Date Incurred** sorting which does not factor in the values for the Schedule D debt records
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVJ6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b0beb622a551c789277bec90ecc10265b1e01ca3/image.png)
2. Fix the **Balance** column sorting.

**DEV Notes**
The backend needs to be revamped so that sorting works  across the transaction_schedulec and transaction_scheduled tables with different column names for the same sort. Maybe a table sql union with a column name alias to sync up the table column names?

### Design ###
null

 See full ticket and images here: [FECFILE-630](https://fecgov.atlassian.net/browse/FECFILE-630)

**Comment by Elaine-Krauss-TCG** [comment]
After a review of the sorting of the Loans and Debts table, I have identified that the "balance" column was not sorting.  This has been fixed.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGhuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b162e0e9abdf39a33be37bbae1bf2eeba26ca36/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the fix for Loans and Debts transactions table sorting by "Date Incurred" and "Balance"
Descending:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2gyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38e6b9cf98ddca795560f3a2229d69e6bc65e74a/image.png)

Ascending:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3AyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79910818fc1feffbb18ddd4d257323cdc816a284/image.png)

Balance ascending:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3gyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca2ab875c9919ab4f6769822b401f13c5abda9f5/image.png)

Balance decending:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzEyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eafa7a2f46f3e71b728cc4581ecd898555d96482/image.png)

QA review retested the sorting of the columns for Loans and Debts all working correctly.

QA Review Completed.   Moved to Stage Ready.
