### ISSUE TITLE
Copy Purpose of Receipt from original transaction to memo text when transaction is copied for Reattribution

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1414]
Business Reason

As a user, I will be able to see the text from the Purpose of Receipt on the original transaction copied to the memo text of the new copied transaction when I reattribute a transaction so that I don't lose any information from the original transaction.

Acceptance Criteria

***Given*** a Purpose of Receipt has been entered on a receipt

  ***When*** the user reattributes that receipt (whether it is from a previous report or within the current report)

  ***Then*** the original Purpose of Receipt will be copied to the Memo Text field as follows:

*   "[Original purpose description: XX] YY" where:

       --XX is the original purpose description (anything in brackets is not editable) 
      *   and YY would be optional memo text (editable).

***And*** YY will be editable to the user (but _not_ the copied purpose description).

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

[FECFILE-611](https://fecgov.atlassian.net/browse/FECFILE-611)

**Comment by mjtravers** [comment]
This ticket is paired with #1415, which is back In Progress. It will move forward to QA when #1415 is ready.
Placing this ticket on hold in the meantime.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers placing ticket on hold

**Comment by WiseQA** [comment]
During QA review the PURPOSE OF RECEIPT (OPTIONAL) text was copied from original transaction to NOTE OR MEMO TEXT (OPTIONAL) field once the "Party Receipt" transaction was reattributed.  (Added the steps below to test this functionality)

1.  Created a Party Receipt transaction, then save
2.  Select "Reattribute" from kabob then save Reattributed to and Reattributed from (NOTE these steps have to be done in order to pass this ticket) then save both transactions.
3.  Select the Original "Party Receipt" transaction from the "Transactions in this report" table and verify the PURPOSE OF RECEIPT (OPTIONAL) text was copied from original transaction to NOTE OR MEMO TEXT (OPTIONAL).   (NOTE:  Verified if test already existed it NOTE OR MEMO TEXT (OPTIONAL) field the text is still displayed correctly.

<img width="682" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk1rQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5e8ae6e27bc14805281d17e3fc544dbdb1734d6/image.png" alt="image.png" />

_________________________________________________________________________________________________________________________

During QA / DEV review the following bugs were found.

1.  When deleting text in the NOTE OR MEMO TEXT (OPTIONAL) field, verbiage is duplicated

<img width="816" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEVrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2309adf2ce184124ccc2f3131e2fea2047cff236/image.png" alt="image.png" />

__________________________________________________________________________________________________________________________
2.  When selecting text in the NOTE OR MEMO TEXT (OPTIONAL) field the select the "delete" key from the keyboard, the field becomes a required field "This is a required field" but is an OPTIONAL field

<img width="608" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f25d98ffd69bf4b9cb879d83470712efaf52b3c/image.png" alt="image.png" />

_________________________________________________________________________________________________________________________

3.   Original COMMITTEE NAME is changed when creating a Reattribute to / Reattribute from transaction.  The original transaction name was "Party Receipt - Test Redesignation - Second Test" and was changed to "Party Receipt - Test Redesignation.


<img width="1368" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGtrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2af60b67a7af6022b6da3576a2aaebcbffab305c/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________
@MitchellTCG @mjtravers verified above fixes, returning to In-Progress for fixes.    These fixes also impact ticket #1415 and needs updated.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA verified the following bugs were fixed.

1.  When deleting text in the NOTE OR MEMO TEXT (OPTIONAL) field, verbiage is duplicated

<img width="816" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEVrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2309adf2ce184124ccc2f3131e2fea2047cff236/image.png" alt="image.png" />

__________________________________________________________________________________________________________________________
2.  When selecting text in the NOTE OR MEMO TEXT (OPTIONAL) field the select the "delete" key from the keyboard, the field becomes a required field "This is a required field" but is an OPTIONAL field

<img width="608" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f25d98ffd69bf4b9cb879d83470712efaf52b3c/image.png" alt="image.png" />

_________________________________________________________________________________________________________________________

3.   Original COMMITTEE NAME is changed when creating a Reattribute to / Reattribute from transaction.  The original transaction name was "Party Receipt - Test Redesignation - Second Test" and was changed to "Party Receipt - Test Redesignation.


<img width="1368" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGtrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2af60b67a7af6022b6da3576a2aaebcbffab305c/image.png" alt="image.png" />

QA Review Completed.  Moved to Stage Ready.
