### ISSUE TITLE
Allow user to create a PDF/print preview of the Form 24 report

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1498]
Business Reason

As a user, I will be able to generate and view a PDF of my report so that I can see how Form 24 looks as a paper form.

Acceptance Criteria

***Given*** a Form 24 report

  ***When*** the user goes to the "Print preview" page

  ***Then*** they can generate a PDF of their report in it's current state

  ***And*** when they click to generate a PDF, they will receive a message indicating "This may take a moment..."

  ***And*** if after 5 seconds the PDF:

*   IS ready: the user will have the option to download it as a PDF by opening it in a new tab; the system will provide a date/time stamp for when the PDF was generated; and the button to compile a new PDF will be available.
*   IS NOT ready: the system will indicate that "Your report is still being processed. Please check back later to access your PDF" and the process will continue in the background until it is ready _(Dev note: check status endpoint each time page is accessed)_

***And*** once the URL is no longer available from WebPrint service _(after 24 hours)_, the page resets _(only one button for Compile PDF)_.

Dev Tasks

The report-web-print component should be moved out of the reports/f3x directory and moved into the reports/shared directory to be used by all reports. Rename the component from "report-web-print" to "print-preview" and the referencing routerLink definitions should be updated to /reports/print-preview

The layout/sidebar/menu-report will need to be refactored into 2 sidebars, one for f3x and one for f24, and also update manage of sidebarState values in the ngrx store. The current menu-report can be the one for f3x.

Create an endpoint on the webservice worker to submit a fec file to the FEC WebPrint service. Return the WebPrint response to the Celery broker

Documents: [https://efoservices.fec.gov/static/webprint_help.html#webservice](https://efoservices.fec.gov/static/webprint_help.html#webservice)
[https://webforms.fec.gov/psa/getstarted.htm](https://webforms.fec.gov/psa/getstarted.htm)

![loading--primary.gif]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a2699e4c-620d-421b-99dc-4a23c382af52](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a2699e4c-620d-421b-99dc-4a23c382af52))

Wireframes

1.  Would you like to compile a print preview?
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGtWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--205f4c350f747748d08c1046839a374ba2dd32d6/1498%20Would%20you%20like%20to.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGtWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--205f4c350f747748d08c1046839a374ba2dd32d6/1498%20Would%20you%20like%20to.png))

1.  Compiling
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG9WQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c680811285b1a1438780081dfd1c63b2f6de2fc/1498%20-%20compiling.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG9WQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c680811285b1a1438780081dfd1c63b2f6de2fc/1498%20-%20compiling.png))

1.  Compiled
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHNWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc0bea7eb32a6118d6d388227ee496c2f0b9bbda/1498%20-%20compilied.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHNWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc0bea7eb32a6118d6d388227ee496c2f0b9bbda/1498%20-%20compilied.png))

1.  Processing
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHdWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b1825d28d43a2c002f9f4b6dd181aa1d9be74f6/1498%20-%20processing.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHdWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b1825d28d43a2c002f9f4b6dd181aa1d9be74f6/1498%20-%20processing.png))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-567](https://fecgov.atlassian.net/browse/FECFILE-567)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg please update images to be the Form 24/Schedule E pages, or remove entirely.

**Comment by MitchellTCG** [comment]
@GreggMoreland 
please review

**Comment by Elaine-Krauss-TCG** [comment]
Webprint submission is working!
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEtxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2998be7e27bf47bd659425303b31c76bec6ab7a9/image.png" alt="image.png" />

<img width="727" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEdxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4ff5d74f5281ae940e385a4b24ecb824c82c331/image.png" alt="image.png" />

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review retested and verified the Print Preview (Placeholder image) PDF have been updated for the Form 24 report. (Note: used test efo filing Committee using login.gov for testing)

<img width="1351" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU8yQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--987612f8b20b5a7dcb51a033dbf8b08b52020fc1/image.png" alt="image.png" />

Compiling:

<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVcyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8885029b12c3a5100e11f12275d9eaaa033cdf56/image.png" alt="image.png" />

Compiled:

<img width="1155" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXEyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdef6fb9894226c8566f62b77bfa52567c38ce35/image.png" alt="image.png" />

Still processing (Note: The screenshot has been updated and verified by DEV and QA. Due to no wait on processing the verification of Print Preview screen passes testing as visual inspection.

<img width="918" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOSsyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86522ee382146aa88ad12562785fd36958734a3f/image.png" alt="image.png" />

QA Review Completed.   Moved to Stage Ready.
