### ISSUE TITLE
Allow user to create a PDF/print preview of the Form 1M report

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1503]
Business Reason

As a user, I will be able to generate and view a PDF of my report so that I can see how Form 1M looks as a paper form.

Acceptance Criteria

***Given*** a Form 1M report

  ***When*** the user goes to the "Print preview" page

  ***Then*** they can generate a PDF of their report in it's current state

  ***And*** when they click to generate a PDF, they will receive a message indicating "This may take a moment..."

  ***And*** if after 5 seconds the PDF:

*   IS ready: the user will have the option to download it as a PDF by opening it in a new tab; the system will provide a date/time stamp for when the PDF was generated; and the button to compile a new PDF will be available.
*   IS NOT ready: the system will indicate that "Your report is still being processed. Please check back later to access your PDF" and the process will continue in the background until it is ready _(Dev note: check status endpoint each time page is accessed)_

***And*** once the URL is no longer available from WebPrint service _(after 24 hours)_, the page resets _(only one button for Compile PDF)_.

Dev Tasks

The report-web-print component should be moved out of the reports/f3x directory and moved into the reports/shared directory to be used by all reports. Rename the component from "report-web-print" to "print-preview" and the referencing routerLink definitions should be updated to /reports/print-preview

The layout/sidebar/menu-report will need to be refactored into 2 sidebars, one for f3x and one for f1m., and also update manage of sidebarState values in the ngrx store. The current menu-report can be the one for f3x.

Create an endpoint on the webservice worker to submit a fec file to the FEC WebPrint service. Return the WebPrint response to the Celery broker

Documents: [https://efoservices.fec.gov/static/webprint_help.html#webservice](https://efoservices.fec.gov/static/webprint_help.html#webservice)
[https://webforms.fec.gov/psa/getstarted.htm](https://webforms.fec.gov/psa/getstarted.htm)

![loading--primary.gif]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a2699e4c-620d-421b-99dc-4a23c382af52](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a2699e4c-620d-421b-99dc-4a23c382af52))

Wireframe

1.  Would you like to compile
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVlOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f9da3c16f726fbe0c86175412e0e8c20262e48b/1503%20-%20Would%20you%20like%20to%20compile.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVlOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f9da3c16f726fbe0c86175412e0e8c20262e48b/1503%20-%20Would%20you%20like%20to%20compile.png))

1.  Compiling your preview
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3daQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eeb5b077df4ad7cbd401a91b3fb861f94e8c59db/1503%20-%20Compiling%20your%20preview.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3daQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eeb5b077df4ad7cbd401a91b3fb861f94e8c59db/1503%20-%20Compiling%20your%20preview.png))

1.  PDF compiled
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWtOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--491c11d79132ade7fec06ae506457cd287a369f9/1503%20-%20PDF%20compiled.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWtOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--491c11d79132ade7fec06ae506457cd287a369f9/1503%20-%20PDF%20compiled.png))

1.  PDF Processing
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2toQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19e390cff295f5c2a77ee70aa544fe2f00feaf25/1503%20-%20PDF%20Still%20Processing.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2toQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19e390cff295f5c2a77ee70aa544fe2f00feaf25/1503%20-%20PDF%20Still%20Processing.png))

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-564](https://fecgov.atlassian.net/browse/FECFILE-564)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
Updates made
Please Review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review retested and verified the Print Preview (Placeholder image) PDF have been updated for the Form 1M report. (Note: used test efo filing Committee using login.gov for testing.

<img width="1279" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFRJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e0c489f7c5e5fa1d0f8abaaf0ee23405b6f448b/image.png" alt="image.png" />

____________________________________________________________________________________________________________________________

Compiling:

<img width="1114" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFhJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79125e24b563acd4f3720a57d24ec400145d911d/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________________

Compiled:

<img width="1185" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGZJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19416a6a37a373f65de4b0dfdff90b1080c0e379/image.png" alt="image.png" />

_____________________________________________________________________________________________________________________________

till processing (Note: The screenshot has been updated and verified by DEV and QA. Due to no wait on processing the verification of Print Preview screen passes testing as visual inspection.

<img width="1049" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG5JQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b967a4d24c3b0dff638c31b3b426f2f9ccb1494/image.png" alt="image.png" />
___________________________________________________________________________________________________________________________

QA Review Completed. Moved to Stage Ready.
