### ISSUE TITLE
Allow user to create a PDF/print preview of the Form 99 report

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1504]
Business Reason

As a user, I will be able to generate and view a PDF of my report so that I can see how Form 99 looks as a paper form.

Acceptance Criteria

***Given*** a Form 99 report

  ***When*** the user goes to the "Print preview" page

  ***Then*** they can generate a PDF of their report in it's current state

  ***And*** when they click to generate a PDF, they will receive a message indicating "This may take a moment..."

  ***And*** if after 5 seconds the PDF:

*   IS ready: the user will have the option to download it as a PDF by opening it in a new tab; the system will provide a date/time stamp for when the PDF was generated; and the button to compile a new PDF will be available.
*   IS NOT ready: the system will indicate that "Your report is still being processed. Please check back later to access your PDF" and the process will continue in the background until it is ready _(Dev note: check status endpoint each time page is accessed)_

***And*** once the URL is no longer available from WebPrint service _(after 24 hours)_, the page resets _(only one button for Compile PDF)_.

Dev Tasks

The report-web-print component should be moved out of the reports/f3x directory and moved into the reports/shared directory to be used by all reports. Rename the component from "report-web-print" to "print-preview" and the referencing routerLink definitions should be updated to /reports/print-preview

The layout/sidebar/menu-report will need to be refactored into 2 sidebars, one for f3x and one for f99., and also update manage of sidebarState values in the ngrx store. The current menu-report can be the one for f3x.

Create an endpoint on the webservice worker to submit a fec file to the FEC WebPrint service. Return the WebPrint response to the Celery broker

Documents: [https://efoservices.fec.gov/static/webprint_help.html#webservice](https://efoservices.fec.gov/static/webprint_help.html#webservice)
[https://webforms.fec.gov/psa/getstarted.htm](https://webforms.fec.gov/psa/getstarted.htm)

![loading--primary.gif]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a2699e4c-620d-421b-99dc-4a23c382af52](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a2699e4c-620d-421b-99dc-4a23c382af52))

1.  Placeholder image (replace fan of 5 form 3x's)
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkVPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3159eeea621d507fab260f57d810b2f2d01e44f/Image%20-Placeholder.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkVPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3159eeea621d507fab260f57d810b2f2d01e44f/Image%20-Placeholder.png))

Wireframes

1.  Would you like to compile
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDhPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41930a451424d609cc7fe5d3f513a4f2ad0e652e/1103%20-%20Would%20you%20like%20to%20compile.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDhPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41930a451424d609cc7fe5d3f513a4f2ad0e652e/1103%20-%20Would%20you%20like%20to%20compile.png))

1.  Compiling
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUFPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f12ebc658be7154e5b93a8a22cc670d984ac4445/1103%20-%20Compiling%20your%20preview.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUFPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f12ebc658be7154e5b93a8a22cc670d984ac4445/1103%20-%20Compiling%20your%20preview.png))

1.  Compiled
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e25761212db93a1b1199e19714ec5d9d8199d3a/1103%20-%20PDF%20ompiled.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e25761212db93a1b1199e19714ec5d9d8199d3a/1103%20-%20PDF%20ompiled.png))

1.  Still processing
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU1PQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7ca33bc888d9ce76011c189fba397619564b469/1103%20-%20PDF%20Still%20Processing.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU1PQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7ca33bc888d9ce76011c189fba397619564b469/1103%20-%20PDF%20Still%20Processing.png))

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
- [x] BA/Design Quality Checklist complete

 See full ticket and images here: [FECFILE-563](https://fecgov.atlassian.net/browse/FECFILE-563)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG on-hold until Hotfix ticket #1557 fixed.  Code will impact this ticket also

**Comment by mjtravers** [comment]
#1557 hotfix finished. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified a PDF for Print preview of Form 99 report is displaying correctly.

1.  Create Form 99 report (NOTE:  if select Save button go to Manage reports and open Form 99. if select Save and continue button Print preview page is displayed)  Tested both ways for display of Print preview pages.  (NOTE: "Compile PDF" Button color will be fixed in a future UX ticket. )

2.  Verified Print preview page "Placeholder image" has been updated.  And verbiage added "Would you like to compile a print preview?"

<img width="1247" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGlJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a75b1c993b84b10844d33b95497c28630cc55f2d/image.png" alt="image.png" />

3.  "Compile pdf" button.  Verified "Compiling your preview" page is displayed.

<img width="1321" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHFJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9afd5ac2f837e955c86f516b81f502d977401f0c/image.png" alt="image.png" />

@mjtravers "Compiling your preview" page is a continual spin not returning PDF Compiled Print preview page.  (NOTE:  if you select refresh the "Compiling your preview" page will quit spinning and take you to PDF Compiled Print preview page)

<img width="1269" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXVJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09096d1136be9e04b481515ef7b2c66727fc664e/image.png" alt="image.png" />

@mjtravers ticket on-hold until hotfix.

**Comment by mjtravers** [comment]
Hotfix made so that the "Compiling your preview" spinner does not spin forever.

**Comment by mjtravers** [comment]
Processing screen updated with hotfix to change image:
(screenshot updated)
<img width="705" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMENNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27be660eecd9e472a75be35e3f01a59338a87133/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA review retested and verified the Print Preview (Placeholder image) PDF have been updated for the Form 99 report. (Note: used test efo filing Committee using login.gov for testing)

<img width="1322" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEtNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5997d1c66e2f2d3394c0e89a2fed60e9b97cabbd/image.png" alt="image.png" />

Compiling:

<img width="1328" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9NQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6a03b45511db47434c1454b42f5197782a46503/image.png" alt="image.png" />

Compiled:

<img width="1307" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFdNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fd21a1cdb0398e697351deeb5be2874aaba538a/image.png" alt="image.png" />

Still processing (Note:  The screenshot has been updated and verified by DEV and QA.   Due to no wait on processing the verification of Print Preview screen passes testing)

<img width="701" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGlNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58e5813994401ab32fbc19c9becee98bb381201e/image.png" alt="image.png" />

@MitchellTCG @mjtravers per conversation a future ticket will be written to fix button color and verbiage consistency where needed.   This ticket passes.

QA Review Completed.   Moved to Stage Ready.

**Comment by mjtravers** [comment]
Removed the work "THE" from form title:
<img width="705" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlNPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ca53e23b26a6b3c1c6fee8365a07ce4a60db72d/image.png" alt="image.png" />
