### ISSUE TITLE
Set Payee Entity default to Individual on Payroll Memo for Independent Expenditure

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1519]
Business Reason

As a user, I will be able to see 'Individual' as the Contact Type entity default in the Payroll Memo for Independent Expenditure so that I can set the value most likely to be used.

Acceptance Criteria

***Given*** I am a user

  ***When*** I am creating a Payroll Memo for Independent Expenditure transaction

  ***Then*** the Contact Type for the Payee is displayed, it shows 'Individual' and 'Organization'

  ***And*** 'Individual' is the default value

### QA Notes ###
- [ ] BA/Design Quality Checklist complete

### DEV Notes ###
 Wireframe
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1BaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32e713d2b65cfe3852aa36b318fd60a8975a4b1f/unnamed.png)

### Design ###
null

 See full ticket and images here: [FECFILE-558](https://fecgov.atlassian.net/browse/FECFILE-558)

**Comment by MitchellTCG** [comment]
I added the clarification for Payee since there are two lookups on the page.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the payee lookup is defaulted to **Individual** instead of **Organization** for the "**Payroll Memo for Independent Expenditure**".   This fix was caught in the Sprint 33 demo by FEC.

Incorrect default lookup  "Organization" for Payroll Memo for Independent Expenditure

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWpuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51210e9e6566c85db6cded711413b11cee44e4a8/image.png)

Correct default lookup  "Individual" for Payroll Memo for Independent Expenditure

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bcdbb69776cf68014a3df7f3f68d9bf9a008c917/image.png)

QA Review Completed.  Moved to Stage Ready.
