### ISSUE TITLE
UX: Remove button/link for "Sign Up" on landing page

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1683]
Task: Remove "Sign up with Login.gov" button hyperlink & and remove "Sign up" button

### DEV Notes ###
-1. Link "Sign up with Login.gov" button to- [-https://idp.int.identitysandbox.gov/sign_up/enter_email-|https://idp.int.identitysandbox.gov/sign_up/enter_email]

### Design ###
h2. Wireframe

!Screenshot 2024-10-11 at 2.05.12 PM (54006ca0-13e5-4395-afbe-4ed0b694b24f).png|width=1891,height=1538,alt="Screenshot 2024-10-11 at 2.05.12 PM.png"!

 See full ticket and images here: [FECFILE-497](https://fecgov.atlassian.net/browse/FECFILE-497)

**Comment by AureliaKhorsand** [comment]
Relevant documentation: 
- https://developers.login.gov/user-experience/sign-in-sign-out/
- https://secure.login.gov/sign_up/enter_email

**Next Steps:** need to directly ask login.gov if this is possible before we can point . @MitchellTCG to create a spike ticket

**Comment by AureliaKhorsand** [comment]
@MitchellTCG Do we have a spike ticket and/or answer for this yet? If not, can we get one created and linked to this?

**Comment by dheitzer** [comment]
@AureliaKhorsand @MitchellTCG currently if we implement this using the link provided above, the user will be taken to their login.gov account page after they sign up (and not back to FECFile).  Is this the expected behavior for this ticket? If we need the user to be taken to FECFile, we will need to ensure login.gov supports this since we rely on them to be redirected to the https://idp.int.identitysandbox.gov link with app context set.

![Image](https://github.com/fecgov/fecfile-web-app/assets/104843885/791eccd5-838f-4c64-b8c5-2b408a5a862f)

**Comment by dheitzer** [comment]
reached out to login.gov to check for support for this feature.
