### ISSUE TITLE
System to default to display Manage Reports page when user is logged in

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#1779]
Business Reason

As a user, I will be able to log in directly to the Manage reports page so that I can quickly see what I need to work on.

Acceptance Criteria

***Given*** a user logs in

  ***When*** the user selects the committee on the committee selection screen

  ***Then*** the system will display 'Manage reports' (instead of the dashboard)

Wireframe

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/110493670/c42964ec-df93-4134-ae7b-c88c6d1e36e2](https://github.com/fecgov/fecfile-web-app/assets/110493670/c42964ec-df93-4134-ae7b-c88c6d1e36e))

### QA Notes ###
- [x] BA/Design Quality Checklist complete

### DEV Notes ###
- System will no longer log in to Dashboard (until a later date when Dashboard is fully defined) and will instead log in directly to 'Manage reports'

### Design ###
null

[FECFILE-465](https://fecgov.atlassian.net/browse/FECFILE-465)

**Comment by MitchellTCG** [comment]
@GreggMoreland 
I've update please review

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified after logging in then select the "Select the committee account" the "Manage reports" page is displayed instead of the dashboard.   

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/27b3283c-ef94-4650-afa2-05276611a60c)

____________________________________________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/b97eaf5b-fb01-4394-a45c-c7fe9c2c49af)

QA Review Completed.   Moved to Stage Ready.
