### ISSUE TITLE
"Form Type" and "Report Type" not sorting correctly on the "Transactions history" table and "Results per page" not displaying transactions if 10 selected

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#1977]
During testing the "Transactions history" table for a contact the "Form type" and "Report type" columns are not sorting correctly.

1\. Screenshot of "Form type" not sorting.

![](/attachments/11287?name=image-20240530-193254.png) [See image in Jira]([https://fecgov.atlassian.net/browse/FECFILE-1400](https://fecgov.atlassian.net/browse/FECFILE-1400)) [See image in Jira]([https://fecgov.atlassian.net/browse/FECFILE-1400](https://fecgov.atlassian.net/browse/FECFILE-1400))

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/cf657728-462f-4093-befc-979fdb2ae24b](https://github.com/fecgov/fecfile-web-app/assets/96139912/cf657728-462f-4093-befc-979fdb2ae24), https://github.com/fecgov/fecfile-web-app/assets/96139912/cf657728-462f-4093-befc-979fdb2ae24b](https://github.com/fecgov/fecfile-web-app/assets/96139912/cf657728-462f-4093-befc-979fdb2ae24))

  _______________________________________________________________________________________________________

2\. Screenshot of "Report type" not sorting.

![](/attachments/11290?name=image-20240530-193316.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/bc03dcc5-dc08-44b7-a2fe-df89549cde5e](https://github.com/fecgov/fecfile-web-app/assets/96139912/bc03dcc5-dc08-44b7-a2fe-df89549cde5), https://github.com/fecgov/fecfile-web-app/assets/96139912/bc03dcc5-dc08-44b7-a2fe-df89549cde5e](https://github.com/fecgov/fecfile-web-app/assets/96139912/bc03dcc5-dc08-44b7-a2fe-df89549cde5))

_______________________________________________________________________________________________________

3\. ***Second part of bug:*** When selecting 5 from the "Results per page" display. The table displays correctly.

![](/attachments/11288?name=image-20240530-193341.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/a0ebff52-67d2-4d73-b6e3-87e8e24303f0](https://github.com/fecgov/fecfile-web-app/assets/96139912/a0ebff52-67d2-4d73-b6e3-87e8e24303f), https://github.com/fecgov/fecfile-web-app/assets/96139912/a0ebff52-67d2-4d73-b6e3-87e8e24303f0](https://github.com/fecgov/fecfile-web-app/assets/96139912/a0ebff52-67d2-4d73-b6e3-87e8e24303f))

4\. Change the selection from 5 to 10 from the "Results per page" display. The table displays incorrectly, still only displays the 5 transactions instead of 10 ***(This is second part of bug)***

![](/attachments/11291?name=image-20240530-193420.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/e258cb15-c149-4c10-8253-6fbde8c94376](https://github.com/fecgov/fecfile-web-app/assets/96139912/e258cb15-c149-4c10-8253-6fbde8c9437), https://github.com/fecgov/fecfile-web-app/assets/96139912/e258cb15-c149-4c10-8253-6fbde8c94376](https://github.com/fecgov/fecfile-web-app/assets/96139912/e258cb15-c149-4c10-8253-6fbde8c9437))

5\. ***Third part of bug:*** Change "Report Type" name for Form 24 from "undefined hour" to "24 Hour" or "48 Hour"

![](/attachments/11289?name=image-20240530-193444.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/46224217-307d-4982-ae2a-eb7cec2fd071](https://github.com/fecgov/fecfile-web-app/assets/96139912/46224217-307d-4982-ae2a-eb7cec2fd07), https://github.com/fecgov/fecfile-web-app/assets/96139912/46224217-307d-4982-ae2a-eb7cec2fd071](https://github.com/fecgov/fecfile-web-app/assets/96139912/46224217-307d-4982-ae2a-eb7cec2fd07))

_________________________________________________________________________________________________________________

![](/attachments/11292?name=image-20240530-193516.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/f8c215eb-ee7e-47e2-ae58-bac5a2c7b30c](https://github.com/fecgov/fecfile-web-app/assets/96139912/f8c215eb-ee7e-47e2-ae58-bac5a2c7b30), https://github.com/fecgov/fecfile-web-app/assets/96139912/f8c215eb-ee7e-47e2-ae58-bac5a2c7b30c](https://github.com/fecgov/fecfile-web-app/assets/96139912/f8c215eb-ee7e-47e2-ae58-bac5a2c7b30))

__________________________________________________________________________________________________________________

@MitchellTCG @mjtravers there are 3 bugs for this ticket.

  1\. Fix the Sorting of "Form Type" and "Report Type" in the Transactions history table. 

  2\. Second part of bug fix the "Results per page" display. 

  3\. Third part of bug fix the "Report type" display correctly for Form 24 (24 Hour / 48 Hour)

  4\. Bug found in testing for Sprint 43\. Pointed 3 point and assigned to Sprint 43.

### QA Notes ###

 
  
  
  
 null

### DEV Notes ###

 
  
  
  
 There are 3 parts to this bug fix

### Design ###

 
  
  
  
 null

 See full ticket and images here: [FECFILE-1400](https://fecgov.atlassian.net/browse/FECFILE-1400)

**Comment by sasha-dresden** [comment]
The issue with form type and report type not sorting is because Form 24 transactions are tied to both a Form 24 and a Form 3X report, so it's a bit wonky on sorting those. I'm wondering if we should have it default to one or the other, so perhaps all Form 24 transactions show as Form 24? Currently it's showing Form 3X for some and Form 24 for others seemingly completely randomly.

In the screenshot all three of these were created in a Form 24
![image](https://github.com/fecgov/fecfile-web-app/assets/149604256/ca6087c2-a31b-4a11-a276-67812de3c379)

**Comment by AureliaKhorsand** [comment]
From a requirements perspective, we know that an independent expenditure will _always_ be on a Form 3X, and _may_ also be on a Form 24. If we default to just showing one of the two, I recommend defaulting to Form 3X, and if we want to show the Form 24 versions as a separate enhancement (relevant for when we figure out the All Transactions Table), then we can do it later. @MitchellTCG thoughts?

**Comment by mjtravers** [comment]
From CR, there are a few issues with the report labels that need to be sorted out:

1) The front-end is not utilizing the report_code_label annotation being passed from the back-end but rather using it's own hard coded labels for F3X in F3X_REPORT_CODE_MAP. The report labels for the F99, F1M, and F24 are handled with the reportLabel() method in their model classes which do not factor into the sorting. The front-end labels for all reports should be removed and added into the sorting mechanism in the back-end. Currently, sorting is only performed for reports on the F3X labels:


![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/b82dd5d6-a15f-4691-b408-72b7eee64d7b)

2) There are 2 report label lists defined in the back end. The first is reports.views.report_code_label_mapping ([see here](https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/reports/views.py#L17-L43)) whose sort values do not match the display values in the front-end (see note 1 above). The second is transactions.managers.report_code_label_mapping ([see here](https://github.com/fecgov/fecfile-web-api/blob/feature/1977/django-backend/fecfiler/transactions/managers.py#L42-L68) ) whose values do match the being used on the front-end for F3X but this list is only used to add the report label to the transactions, does not include non-F3X reports, and is only used in the transaction table on the contact screen. The lists should be merged and the non-F3X labels need to be added. This will be tricky because those reports do not have values in the reports_report.report_code column:


![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/618f729c-587c-40f9-bd3e-28ec7b8fa28a)

3) There is a duplication of the report label generation in the transaction and its view. I suspect we can remove the transaction implementation [found here](https://github.com/fecgov/fecfile-web-api/blob/feature/1977/django-backend/fecfiler/transactions/managers.py#L336-L340)

Sending back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
During QA review the Form Type column not displaying associated forms (e.g., Form 24) and the "Report Type" column is blank (no report info displaying).  

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/c1212b18-785f-4932-81b6-6764c105fc22)

@MitchellTCG @mjtravers @sasha-dresden per bug fix returned to in-progress for the above fix.

**Comment by sasha-dresden** [comment]
Ah I forgot we weren't sending over the full report with the transaction. I updated the transaction__report section to include the report_code_label so it can be properly utilized here.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified "Form Type", "Report Type" and "Results per page" bug fix implemented and working as currently designed for the "Transactions history" table for a contact.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/e2769d88-c6ef-4b4d-8d2c-a104e7cab76b)

QA Review Completed.   Moved to Stage Ready.
