### ISSUE TITLE
UI: move "Restore deleted contacts" button and remove 'Contacts' H2

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1981]
Tasks

*   [ ] Remove the "Contacts" H2
*   [ ] Move "Restore deleted contacts" button to the left of "+ Add contact" (20px padding between the buttons)
*   [ ] There should be 16px of space between the bottom of the buttons and top of the Data table
*   [ ] make the background color of the Restore deleted contacts buttons #AEB0B5
*   [ ] Make the text color of the Restore deleted contacts buttons #212121
*   [ ] Rename the button from "Restore deleted contact(s)" to "Restore deleted contacts "

1.  ## Current State

[current-state](#current-state)

[![](/attachments/11259?name=image-20240530-172007.png) [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1404)| /attachments/11259?name=image-20240530-172007.png] [![](https://github.com/fecgov/fecfile-web-app/assets/25588182/577a5031-35b0-4df7-a57d-e6033ff03961%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/577a5031-35b0-4df7-a57d-e6033ff0396))](https://github.com/fecgov/fecfile-web-app/assets/25588182/577a5031-35b0-4df7-a57d-e6033ff03961%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/577a5031-35b0-4df7-a57d-e6033ff0396))

1.  ## Ideal State

[ideal-state](#ideal-state)

[!image-20240530-172101.png! [See image in Jira](https://fecgov.atlassian.net/browse/FECFILE-1404)| /attachments/11260?name=image-20240530-172101.png] [![](https://github.com/fecgov/fecfile-web-app/assets/25588182/199da90b-9106-45e0-8206-5e8b4c69a349%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/199da90b-9106-45e0-8206-5e8b4c69a34))](https://github.com/fecgov/fecfile-web-app/assets/25588182/199da90b-9106-45e0-8206-5e8b4c69a349%5D(https://github.com/fecgov/fecfile-web-app/assets/25588182/199da90b-9106-45e0-8206-5e8b4c69a34))

### QA Notes ###

- [x] BA/Design Quality Checklist complete

### DEV Notes ###

 Design

### Design ###

null

[FECFILE-1404](https://fecgov.atlassian.net/browse/FECFILE-1404)

**Comment by MitchellTCG** [comment]
@GreggMoreland pls review

**Comment by sasha-dresden** [comment]
@MitchellTCG on #1988 and #1989 it says to have 8px padding below the H1 and the top of the table, but on this ticket, it asks for 16px between the action buttons, (which are on the same line as the H1). I wasn't sure if this table was specifically different from all the others or if one of the spacings was incorrect? 
Also, I noticed that the alignment between the H1 and the buttons is baseline, which seems a little off to me when the padding is much smaller. This is because baseline aligns the text of the button and the text of the h1 on the baseline, which because "Manage Users" has a descending "g", so the padding between the h1 and the table looks much larger than the padding between the buttons and the table.

![Image](https://github.com/fecgov/fecfile-web-app/assets/149604256/58ffc556-ab34-46e9-971a-d91c75fbe2ef)

Trying out the various options, I think this looks a bit more even: This is set to end 

![Image](https://github.com/fecgov/fecfile-web-app/assets/149604256/193fba30-a0c2-4f35-afaa-2625212767da)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the following UX changes were implemented.

*   [x] Remove the "Contacts" H2
*   [x] Move "Restore deleted contacts" button to the left of "+ Add contact" (20px padding between the buttons)
*   [x] There should be 16px of space between the bottom of the buttons and top of the Data table
*   [x] make the background color of the Restore deleted contacts buttons #AEB0B5
*   [x] Make the text color of the Restore deleted contacts buttons #212121
*   [x] Rename the button from "Restore deleted contact(s)" to "Restore deleted contacts "
_______________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/76478ae2-e013-4c8f-8160-b70bd352b1f5)

_______________________________________________________________________________________

QA Review Completed.  Moved to Stage Ready.
