### ISSUE TITLE
Allow users to view existing users

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#201]
Business Reason

As a Committee Administrator, I will be able to view existing users in my Committee Account so that I can manage them appropriately.

UPDATED Acceptance Criteria

***Given*** I am a Committee Administrator

  ***When*** I access the user management page

  ***Then*** I will able to see existing users for the Committee Account, including:

*   Name
*   Email
*   Role
*   Status

***And*** the list will be sorted alphabetically (A-Z) by name in ascending order.

Dev Note

Please make the Name column sortable by ***Last Name***, First Name

_Note: Additional functionality will be later features._

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1242](https://fecgov.atlassian.net/browse/FECFILE-1242)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg This is the story that will eventually need the Manage Users wireframe you all have been working on.

**Comment by AureliaKhorsand** [comment]
![image.png](https://images.zenhubusercontent.com/61a50e5fdcda4774a0cf2a0e/3d185fdd-fbdc-4bff-a06d-2c5cbf2851d9)

**Comment by AureliaKhorsand** [comment]
**4/6/22 Refinement Meeting:** This ticket covers functionality and not specific look-and-feel. Clarified that users should only see users from the Committee Account they are logged in to and not others.

**Comment by Elaine-Krauss-TCG** [comment]
To-do list:
- [x] Implement an endpoint that allows the user to retrieve a list of users in the same committee
- [x] Implement a new front-end component per the wireframe
- [x] Add unit tests for code coverage

**Comment by Elaine-Krauss-TCG** [comment]
Pull requests open for this ticket on the [Front-End](https://github.com/fecgov/fecfile-web-app/pull/337) and the [Back-End](https://github.com/fecgov/fecfile-web-api/pull/143)

For QA: You can find the results of the unit tests [here](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/482/workflows/4b007b0c-76d5-48c4-9d5a-37cc3a19cabe/jobs/1342)

**Comment by mjtravers** [comment]
Elaine, this looks great. There are a handful of requested changes noted in the PR from my and Todd's code reviews. You can click the "Resolve conversation" button as you work out what is being asked in the comment. Also, the api PR has a merge conflict that needs to be resolved. Sending ticket back to "in progress".

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
Per conversation with @mjtravers and @Elaine-Krauss-TCG ticket #201 returned to add test data to Exiting User's table.  For reference from our conversation ticket #105 has a list of committee IDs and User's currently needing data for testing.

**Comment by mjtravers** [comment]
A couple of changes requested from CR. [See PR for details](https://github.com/fecgov/fecfile-web-api/pull/148). Moving ticket to In Progress

**Comment by toddlees** [comment]
### The Problem ###
QA needs records in the user table to test this feature.

### Possible Solutions ###
The most obvious way to achieve this is to make a migration that loads a fixture of users into the database.  This method worked for tables like f3x and transactions, but runs into an issue with the user table that would require a small amount of coding effort but a good amount of devops verification to correct.  I'll skip over the details of that (you can see the details below), but it means that if we want to load the users that way, we opt into the work of refactoring the db spin up.

@MitchellTCG what we didn't discuss (and this is because I hadn't looked into why we were doing this migration in the first place) was an alternative to the migration.  We could manually go into dev/stage/prod and load the fixtures. Elaine and I could do this in a 30 minute session i think.  Just an option if you want to move this through without tackling the big problem of the migrations in the uat db.

### Where we are now ###
We've decided to put this on hold.  The issue preventing the migration+fixture solution will be easier to solve with the deployment of the login.gov feature.  @MitchellTCG let me know if the alternative i suggested above is enticing enough that you'd like us to go forward with it.


### Details on Migration Issue ###
The uat database dump that we use to start up the Dev, Stage, Prod environments has a Django Migration history.  This history combined with the actual migrations (python scripts that should be in the codebase) make the tables flexible and let us make changes in our code without making tricky and hazardous changes directly on the database.  We don't have the original migration scripts though.  They were not in the codebase we inherited.  `The database dump with the migration history is actually preventing us from using the Django migration feature on the users table`.  Essentially it's in a corrupted state.  We need to either clean up the uat database dump manually or start with a fresh database.  Option 1 (clean up uat db) is quicker and we keep the test user accounts.  There is the possibility that the uat db has other similar issues with it that we'll need to fix if they conflict with our development efforts.  Option 2 (fresh db) is only a little more effort after we move to the login.gov paradigm.  It's a bit more effort if we try to tackle it before the login.gov change.  We would need to replace the user accounts that people use to get into the app. The boon with option 2 is that we would have a db that only has tables and records that we've defined, meaning we could not be blindsided by issues in the inherited db image.

**Comment by MitchellTCG** [comment]
@Elaine-Krauss-TCG  will demo this ticket

**Comment by toddlees** [comment]
@MitchellTCG We went with the second option that I described in the writeup above.  Currently the test users have been loaded onto the development environment.  When this ticket goes to stage, we will need to manually load the test users.

**Comment by WiseQA** [comment]
QA review completed on this ticket.   Manage User's table included Name, Email, Role and Status.   User's name sortable A-Z (Ascending and Descending)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/4c32d43e-67a5-4010-bbb8-989cbb12ef06)

QA review completed.  Moved to Stage Ready.

**Comment by MitchellTCG** [comment]
@Elaine-Krauss-TCG 

Talked with Matt, he says the error is on line 36

Also please replace Shelly's test data with the test data under Ryan's 00474387 account.

Shelly's users al have the same last name so it was easy to miss the fact that user names were not sort on last name but first name instead.

**Comment by Elaine-Krauss-TCG** [comment]
Users are now sorted by name according to "Last, First" instead of "First Last"
The fixture providing dummy-users for testing this functionality has been modified to provide unique last names for each created user.

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/bb5c755f-40c5-463c-9778-cfed02b959a6)

**Comment by mjtravers** [comment]
Passes CR. The DEV server is showing the new records for Shelly's account. Sending to QA.

**Comment by WiseQA** [comment]
QA review completed on this ticket. Manage User's table included Name, Email, Role and Status. User's name sortable A-Z (Ascending and Descending).  Name column sortable by Last Name, First Name.

Decending:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0814fe18-cbf7-43ee-a2a5-25e48382b5e5)

Ascending:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8e861dc4-fe70-4e56-985a-b34dd942911a)

QA review completed.  Moved to Stage Ready.
