### ISSUE TITLE
Link pages to Report Left Side Navigation

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#350]
Purpose

Create the Report Workflow Accordion Side Navigation.

Business Reason

As a Committee Administrator, I will be able to navigate thru the Form3X report workflow. I will be able to move back and forth through the workflow

Dev Notes

This is base on the FEC Pattern library component
[https://fec-pattern-library.app.cloud.gov/components/detail/side-navigation.html](https://fec-pattern-library.app.cloud.gov/components/detail/side-navigation.html)

  The angular routes may have to be revisited if information that is needed in the current routes is missing. (e.g. :reportId)

Building Specs

### QA Notes ###
**Accordion Navigation**

**Tier 1:**
ENTER A TRANSACTION  - [ALL CAPS]
- Manage your transactions _(Go to View All Transactions for report)_
- Add a receipt _(Go to Add a Transaction screen)_
- Add a disbursements [30% Opacity] **(NOT BUILT YET-LEAVE UNLINKED)**
- Add loans and debts [30% Opacity] **(NOT BUILT YET-LEAVE UNLINKED)**
- Add other transactions [30% Opacity] **(NOT BUILT YET-LEAVE UNLINKED)**

**Tier 2:**
REVIEW A REPORT
- View summary page _(Go to Summary Page)_
- View detailed summary page _(Go to Detailed Summary Page)_
- View print preview _(Go to PDF/Print Preview page)_**(NOT BUILT YET-LEAVE UNLINKED)**
- Add a report level memo _(Go to Report Level Memo page)_**(NOT BUILT YET-LEAVE UNLINKED)**

**Section 3:**
SUBMIT YOUR REPORT
- Confirm information _(Go to Email and Verify Address page)_
- Submit report _(Go to Sign and Submit page)_
- Report status _(Go to Report Submission Status Page)_

## QA Notes ##
To display the report management menu in the left sidebar, click on "Reports" in the top menu and edit a report.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1152](https://fecgov.atlassian.net/browse/FECFILE-1152)

**Comment by mjtravers** [comment]
@WiseQA The left sidebar navigation is disappearing when a user edits a report transaction. The fix for this is a bit involved with the renaming of page URLs and their interaction with the data to pull the report and transaction IDs. I suggest we open a new ticket to address adding the edit transaction screens so that the "ENTER A TRANSACTION" -> "Add a receipt" menu stays highlighted for those screens.

Also, the memo ticket [app#166](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/166) is still In Progress so the link for that page in the sidebar menu ("Add a report level memo") has been disabled until it is completed and passes CR. It will not be testable with this ticket.

The issue with the edit transaction screens is being worked on in ticket 415: https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/415

**Comment by mjtravers** [comment]
Passed CR with known issues regarding the edit transaction screens and the memo screen. (See comment above.) Sending to QA

**Comment by WiseQA** [comment]
Per discussion with @mjtravers updated Acceptance Criteria with verbage "(NOT BUILT YET-LEAVE UNLINKED)" for consistency and ease of review what has and has not been built out.   

QA Review completed, visual inspection completed.  

QA completed moved to Stage Ready.
