### ISSUE TITLE
Allow user to enter Partnership Receipt Joint Fundraising Transfer Memo on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#449]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **"Partnership Receipt Joint Fundraising Transfer Memo"** sub-transaction under **"Joint Fundraising Transfers"** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a Tier 2 transaction that will be associated with a Tier 1 transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator
**And** I am editing a Joint Fundraising Transfer transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction:
- Partnership Receipt Joint Fundraising Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only)
-- ORGANIZATION
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required, system checked and read-only)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) 
-- within Aggregation Group of "GENERAL"
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Read-only, System-generated)
-- If transaction has no associated Partnership memos, reads "JF Memo: XX (Partnership attributions do not require itemization)". 
--If transaction has associated Partnership memos, reads "JF Memo: XX (See Partnership Attribution(s) below)"
--and XX is auto-populated with name of committee entered in parent/Tier 1 transaction JF_TRAN COL SEQ 8.
-	**NOTE OR MEMO TEXT** ( Optional)

---
**Then** I will be able to:

- Save & Add Memo _(Note that this is a transaction with a possible tier 3 transaction)._
-- Group Name: Joint Fundraising Transfer Memo; Memo name list: Individual, Party, PAC, Tribal, Partnership Receipt
-- Group Name: Partnership Receipt JF Transfer; Memo name list: Partnership Individual
- Cancel
- Save
- Edit 

**And if** the Aggregate amount is >= $200.01 or negative,
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA12.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- Purpose of Receipt will be different depending on if there are sub-transactions added to this transaction or not.
- There should be italics text under the Purpose of Receipt title (see Wire)
- Tier 3 link for "Partnership Individual" under "Save & Add Memo" will be dead links until we build that transaction.

 Dev Note 

- There should be italics text under the CPD title (see Wire)
- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [ ] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=712318747)

 Wireframe 
 
![449 - Partnership Receipt Joint Fundraising Transfer Memo.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e4853523-0527-47ae-981d-f36bde5392d6)

# + Save & add memo Dropdown 
#
![449 - Partnership Receipt Joint Fundraising Transfer Memo Dropdown.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/b11712f5-10d1-4a9c-9475-44afa14e1039)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by mary-tcg** [comment]
@AureliaKhorsand @MitchellTCG @GreggMoreland updated wireframe

**Comment by AureliaKhorsand** [comment]
Marked as high priority so that it is done _before_ other transactions of this kind (with Tier 3 transactions).

**Comment by MitchellTCG** [comment]
Wires are up-to-date

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Prerequisite  a Joint Fundraising Transfer transaction to be created, saved in the "Transactions" table.  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/644765c2-f215-4b5d-b558-0f44ce1c3a05)

Select the + Save & add memo button. Verify dropdown list is displayed.  Then select "Partnership Receipt" from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d2753e9c-2b8f-4f8f-8a18-2182703cb42c)

Verify "Partnership Receipt Joint Fundraising Transfer Memo" page is displayed and contact type is "Organization" only

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/186f8b3e-e108-45b3-ae0f-1c45fa91cece)

Verified text - PURPOSE OF RECEIPT (SYSTEM-GENERATED)
If transaction has no associated Partnership memos, reads "JF Memo: XX (Partnership attributions do not require itemization)". Otherwise, reads "JF Memo: XX (See Partnership Attribution(s) below)"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c4780134-6407-411b-a978-06ff55bc6c8d)

Select + Save & add memo under the "Partnership Receipt Joint Fundraising Transfer Memo" transaction created.   Verify dropdown list is displayed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9ee390db-9701-4499-9a94-3a813197d912)

**Comment by WiseQA** [comment]
@MitchellTCG QA question is the 3rd teir button suppose to say + "Save & add more" Dropdown as denoted above, or is the button "+ Save & add memo" ?    

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/20412eac-0d1e-4707-9eeb-4182330fbd71)

@MitchellTCG please verify what is suppose to be displayed.

Also when I select the "PURPOSE OF RECEIPT (SYSTEM-GENERATED)" text box the following error is displayed.  Unable to "Save" transaction"

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a0d31238-7943-4e96-8f7f-ed890843b071)

@MitchellTCG @mjtravers @toddlees returning to In-Progress.   The error received from "PURPOSE OF RECEIPT (SYSTEM-GENERATED)" text box causes it unable to "Save" transaction"

**Comment by MitchellTCG** [comment]
@WiseQA let's chat in the morning. I didn't get an ellipsis at the end of my message in the purpose of receipt field. plus the character count doesn't seem to warrant and ellipsis. And i guess that is why mine could save. not sure. let's talk.
![Screenshot 2023-04-30 at 1.36.20 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/a26be7c8-bfb3-436e-99c5-d92a72027540)
![Screenshot 2023-04-30 at 1.36.30 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/e95ab096-815f-467b-a4d1-56856c12182e)

**Comment by WiseQA** [comment]
QA Review there was a question asked and a bug reported.

@MitchellTCG 
Question asked was about the dropdown:

QA question is the 3rd teir button suppose to say + "Save & add more" Dropdown as denoted above, or is the button "+ Save & add memo" ?

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/156b91cf-ae65-4ed8-9f8b-3587f9dc014e)image.png

@MitchellTCG please verify what is suppose to be displayed.

**Comment by WiseQA** [comment]
QA review bug found for this ticket and returned for fix.  Below is just the bug found.

Also when I select the "PURPOSE OF RECEIPT (SYSTEM-GENERATED)" text box the following error is displayed. Unable to "Save" transaction"   

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d9f7749d-fdb7-46eb-9711-ce90e1b11f9c)

The wording in the text box is not complete and not completed.   Itemization.) is cut off

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/773adfd7-64e2-4c2e-8d06-a25fc65f395f)

@MitchellTCG @mjtravers @toddlees returning to In-Progress. The error received from "PURPOSE OF RECEIPT (SYSTEM-GENERATED)" text box causes it unable to "Save" transaction"

**Comment by MitchellTCG** [comment]
@WiseQA 
Hey I mistyped the title in the wireframe. "+ Save and a memo" is correct.

**Comment by AureliaKhorsand** [comment]
Decision requested from FEC on 5/1: 

1. (Low level of dev effort): If the committee name happens to be long and the text runs over 100 characters, the schema validation will just make sure that “JF Memo:” is present with text that follows, and accept that the text is truncated at the end. So, for example, the screenshot above would pass. Example: “JF Memo: Really Long Test Committee Name (Partnership attributions do not require…”
2. (High level of dev effort): If the system determines that the text will run over 100 characters, the system will truncate the committee name so that whatever is in parentheses will fit. Example: “JF Memo: Really Long Test Com… (Partnership attributions do not require itemization)”

**Currently awaiting response.**

**Comment by AureliaKhorsand** [comment]
Decision from FEC over email on 5/1: If the system determines that the text will run over 100 characters, the system will truncate the committee name so that whatever is in parentheses will fit. Example: “JF Memo: Really Long Test Com… (Partnership attributions do not require itemization)”

ACs describing this functionality will be included in all similar transaction tickets:

**If** the Purpose of Receipt surpasses the 100 character limit, 
**then** the system will truncate the committee name (XX text) and end it with "..." so that everything in the parentheses can fit.

**Comment by mjtravers** [comment]
Patch for truncating long description passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review retested.

Prerequisite a Joint Fundraising Transfer transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3dc7ae4d-0419-4887-b6c5-18ed3679dec0)

Select the + Save & add memo button. Verify dropdown list is displayed. Then select "Partnership Receipt" from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1e2b283d-d537-4c5e-a2a3-feeaf4f96004)

Verify "Partnership Receipt Joint Fundraising Transfer Memo" page is displayed and contact type is "Organization" only

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1450c951-3026-4344-a6ad-351a3495f099)

Verified text - PURPOSE OF RECEIPT (SYSTEM-GENERATED)
If transaction has no associated Partnership memos, reads "JF Memo: XX (truncated if long name ". . . " (Partnership attributions do not require itemization)". 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0127bc6c-442d-43d8-b812-201d2f51d045)

Select + Save & add memo under the "Partnership Receipt Joint Fundraising Transfer Memo" transaction created and displayed in the transactions table.

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/76758f0f-71e3-443c-a04d-2acdeb60c3b7)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ab71f7a1-f3cb-4ab1-affa-1d95c867ebf4)

QA Review Completed. Moved to Stage Ready.
