### ISSUE TITLE
Allow user to enter Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#468]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **”Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo”** sub-transaction under a **”Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a Tier 2 transaction that will be associated with a Tier 1 transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account on an open report  
**Then** I will have the option to enter the following sub-transaction: 
- Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, includes LOOKUP)
-- Organization 
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required, system checked and read-only)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Recount Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_RECOUNT_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Read-only, system generated)
-- If transaction has no associated Partnership memos, reads "Recount/Legal Proceedings Account JF Memo: XX (Partnership attributions do not require itemization)". 
--If transaction has associated Partnership memos, reads "Recount/Legal Proceedings Account JF Memo: XX (See Partnership Attribution(s) below)"
--and XX is auto-populated with name of committee entered in parent transaction JF_TRAN COL SEQ 8.
**-- Note: If the Purpose of Receipt surpasses the 100 character limit, then the system will truncate the committee name (XX text) and end it with "..." so that everything in the parentheses can fit.**
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Save & add memo _(Note that this is a transaction with a possible tier 3 transaction)._
-- Group Name: Joint Fundraising Transfer - National Party Recount/Legal Proceedings ; Memo name list: Individual, Party, PAC, Tribal, Partnership Receipt
-- Group Name: Partnership Receipt Recount/Legal Proceedings Account JF Transfer; Memo name list: Partnership Individual
- Save
- Edit 

**And if** the Aggregate amount is >= $200.01 or negative,
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA17.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note 

First Tier 3 Transaction tested for JF Transfer Memo's.  

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=207232290)

 Wireframe 

![468 - Partnership Receipt Recount-Legal Proceedings Account JF Transfer Memo.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/56d5a459-f1cb-4668-9715-d2ebbc584e43)

# + Save & add memo Dropdown 
#
![468 - Partnership Receipt Recount-Legal Proceedings Account JF Transfer Memo – Dropdown.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/ef433e39-bdef-4376-976e-aab98b67de92)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Updated

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Wires Updated

**Comment by AureliaKhorsand** [comment]
@MitchellTCG since this is a Partnership transaction, it needs the additional explanation text under "Purpose of Receipt" indicating that the text may be different depending if there are additional Tier 3 memos or not. See #449

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Wires Updated

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Prerequisite a "Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account" transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c1417a52-2ea1-4aaf-95bd-8345f960554b)

Select the + Save & add memo button. Verify dropdown list is displayed. Then select "Partnership Receipt" from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a70c2b03-4285-432b-a175-a2adc7ba7e8f)

Verify "Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo" page is displayed and contact type is "Organization" only

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b4412cd3-c618-475d-aed1-cf1037c83e12)

Verified text - PURPOSE OF RECEIPT (SYSTEM-GENERATED) text displayed:
If transaction has no associated Partnership memos, reads "Pres. Nominating Convention Account JF Memo: XX (Partnership attributions do not require itemization)". Otherwise, reads "Pres. Nominating Convention Account JF Memo: XX (See Partnership Attribution(s) below)"

Add text field contains:

Recount/Legal Proceedings Account JF Memo: ... (Partnership attributions do not require itemization)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/21c6e401-2f99-4ab6-8ca8-85308acc1994)

Verify Tier 3 link for "Partnership Individual" under "Save & Add Memo" selectable.  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8131c89b-ca02-41ad-9dde-7d92a92fa923)

Verify Tier 3 memo is created "Partnership Individual Recount/Legal Proceedings Account JF Transfer Memo"  (Note:  Per AC this is a dead link, even though Transactions page is displayed.   However cannot save transaction. 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0d77bfc7-0ac4-4d16-918e-221a01f1acc5)

Error received when saving transaction.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6ae14dd7-4dfe-44a0-81b1-14c04957ed0b)

On-hold until further discussion with @mjtravers @MitchellTCG as all these transactions are missing the "Associated with" to verify Tier functionality.

**Comment by WiseQA** [comment]
@mjtravers per review, returned ticket to in-progress for fix of error denoted during testing and the "Associated with"  not displaying in the transactions table.

**Comment by mjtravers** [comment]
Fixes for pop up error message and missing Associated With ids made. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Retested this ticket after fixes.   This Tier 3 transaction is live and developed.

Prerequisite a "Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account" transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d935a0ef-91e8-42f1-bd9d-d65a60160f5b)

Select the + Save & add memo button. Verify dropdown list is displayed. Then select "Partnership Receipt" from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/aac0f6f6-fe30-4d7a-977c-6e377ce92bd3)

Verify "Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo" page is displayed and contact type is "Organization" only

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/57d38be2-1667-433c-bdf6-0f568a393049)

Verified text - PURPOSE OF RECEIPT (SYSTEM-GENERATED) text displayed:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d31536b2-0789-4bee-bcc9-c184a8c06939)

Verify Tier 3 link for "Partnership Individual" under "Save & Add Memo" selectable.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/99c3e199-aca1-4a54-a1eb-044243c1677e)

Verify Tier 3 memo is created "Partnership Individual Recount/Legal Proceedings Account JF Transfer Memo" 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/75eab4f8-5de2-4f82-85c7-c54965fcd64a)

Verified the "Transaction ID" and "Associated with" for tier 3 is displayed and referenced correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c35e57fd-d54b-41c4-aae1-fa06094c41d8)

QA Review Completed. Fixes have been implemented and Pass.  Moved to Stage Ready.
