### ISSUE TITLE
Defect - When viewing the Form 3X Submitted Report status is showing "In-Progress"

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-app#484]
This defect is to correct when viewing the Form 3X Submitted Report page remove status as showing "In-Progress"

This was hard coded, per Elaine comment, remove "In-Progress"

![image.png]([https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/eeb6c484-934d-4d36-b91f-8840580f4b35](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/eeb6c484-934d-4d36-b91f-8840580f4b35))

Note: Initial ticket was #355 in Sprint 12\. Defect found during Sprint Review 12.

1.  1.  QA NOTES ##

             The report status on the reports table should show a change of status depending on where in the workflow and processing of the web upload the report is in for the following:

             Before submitting the report, the status should read:

             "In-Progress"

             After submitting the report, the status should read:

             "Submitted" while FEC works to process the report

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-1078](https://fecgov.atlassian.net/browse/FECFILE-1078)

**Comment by Elaine-Krauss-TCG** [comment]
Per the original ticket, that particular column should read as "Submitted" once the given report has been filed.

 - Should it still read as "In-Progress" _before_ it is submitted?
 - Should it read differently once the report is accepted?
 - Should it read differently if the report is rejected?

**Comment by MitchellTCG** [comment]
I assigned this to @AureliaKhorsand to answer Elaine's questions. plus i will be out tomorrow.

**Comment by AureliaKhorsand** [comment]
@Elaine-Krauss-TCG  here are my answers for now. We have #218 that in theory will address all the possible report statuses, so these may change once we get requirements from FEC. 

- Should it still read as "In-Progress" _before_ it is submitted? Yes
 - Should it read differently once the report is accepted? No, it can stay as submitted for now. Date Filed shows us it is submitted.
 - Should it read differently if the report is rejected? If possible, "Rejected" would be great. Again, as long as we can keep this as a low level fix, since #218 is coming eventually. 

Thanks!

**Comment by Elaine-Krauss-TCG** [comment]
Because this column needs to be able to be sorted, this all has to be done on the back-end.

I decided to solve the problem by creating an annotated value in the f3x_summary viewset.  This is necessary because the statuses returned by the FEC are quite different from the text we want to display, and they won't sort properly if we just fix it with a pipe on the front-end.

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/575c4401-0e05-4717-a3d7-74385833a2fd)

**Comment by Elaine-Krauss-TCG** [comment]
Everything seems to work properly both in smoke testing and in a run of the E2E tests, but more unit tests are needed to get code coverage up.

**Comment by WiseQA** [comment]
QA returned - update QA notes to detail what status show when in the Reports table.   @toddlees per conversation returned to "In-progress".   Currently table not displaying any status.  Updated to 2 - 1 was selected as a placeholder for this ticket.

**Comment by WiseQA** [comment]
@toddlees @Elaine-Krauss-TCG - QA question what does "Failed" mean ?  Should this be part of QA testing steps under QA notes ?
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0e5e7b1e-9712-4a06-bf57-a6de0c0cb87e)

**Comment by WiseQA** [comment]
QA review verified Status shows "In-Progress" and "Submitted" for this ticket.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0c176209-768e-4a7d-9024-8335669868f2)

The following statuses will be developed in a future ticket (#218 as denoted above).
"Accepted" if they accept the report
"Rejected" if they rejected the report

QA Review Completed.   Moved to Stage Ready
