### ISSUE TITLE
Allow user to enter Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#504]
Business Reason 
 
As a Committee Administrator, I will be able to enter a **”Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo”** sub-transaction under a **”Joint Fundraising Transfer - National Party Pres. Nominating Convention Account”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Joint Fundraising Transfer - National Party Pres. Nominating Convention Account on an open report  
**Then** I will have the option to enter the following sub-transaction: 
- Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, includes LOOKUP)
-- ORGANIZATION
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required, system checked and read-only)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Convention Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_CONVENTION_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Read-only, system generated)
-- If transaction has no associated Partnership memos, reads "Pres. Nominating Convention Account JF Memo: XX (Partnership attributions do not require itemization)".
--If transaction has associated Partnership memos, reads "Pres. Nominating Convention Account JF Memo: XX (See Partnership Attribution(s) below)"
--and XX is auto-populated with name of committee entered in Tier 1 transaction JF_TRAN COL SEQ 8.
**-- Note: If the Purpose of Receipt surpasses the 100 character limit, then the system will truncate the committee name (XX text) and end it with "..." so that everything in the parentheses can fit.**
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Save & add memo _(Note that this is a transaction with a possible tier 3 transaction)._
-- Group Name: Joint Fundraising Transfer - National Party Pres. Nominating Convention; Memo name list: Individual, Party, PAC, Tribal, Partnership
-- Group Name: Partnership Receipt Nominating Convention Account JF Transfer; Memo name list: Partnership Individual

- Save
- Edit as needed

**And if** the Aggregate amount is >= $200.01 or negative,
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA17.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note
- Tier 3 link for "Partnership Individual" under "Save & Add Memo" will be dead link until we build that transaction.
- The system-generated text for the Contribution Purpose Description takes up the entire 100 character limit so that the "XX" part of the description will not be displayed, even as a "..."

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=590680592)

 Wireframe 

![504 - Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/502fbc02-dadb-406c-9761-be385f8ea4ac)

# + Save & add more Dropdown 
#
![504 - Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo – Dropdown – 1.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/df69b62c-eba1-4851-8887-85ed8dcecd9c)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Updated

**Comment by MitchellTCG** [comment]
Updated with 2 wires not 1

**Comment by AureliaKhorsand** [comment]
@MitchellTCG since this is a Partnership transaction, it needs the additional explanation text under "Purpose of Receipt" indicating that the text may be different depending if there are additional Tier 3 memos or not. See #449

Also, this just says "Partnership" under the first group in the dropdown, whereas sometimes it says "Partnership Receipt". Which one do we want to go with?

**Comment by MitchellTCG** [comment]
Wires Updated

@AureliaKhorsand 
per our conversation it should read "Partnership Receipt"

**Comment by dheitzer** [comment]
This one needs confirmation on what to do with the CPD: "Pres. Nominating Convention Account JF Memo: (Partnership attributions do not require itemization)" as it is 98 characters (max of 100).

**Comment by AureliaKhorsand** [comment]
@dheitzer (et al.) - for now, we will continue as is with the CPD character limit and our functionality for pulling in information, with the understanding that some committee names may not even show. Paul/Ken have agreed to request a CPD character limit increase from EFO, which will solve most of these issues. More discussions on this forthcoming.

**Comment by dheitzer** [comment]
Thanks @AureliaKhorsand I have implemented as discussed.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Prerequisite a "Joint Fundraising Transfer - National Party Pres. Nominating Convention Account" transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0ac92406-0a4e-4626-b18d-fc0b0594474b)

Select the + Save & add memo button. Verify dropdown list is displayed. Then select "Partnership Receipt" from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/f07a6e44-45a0-4fba-bd55-95d0f930d9fb)

Verify "Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo" page is displayed and contact type is "Organization" only

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fb93ee18-b774-4126-b154-e8ceb4a8ab4a)

Verified text - PURPOSE OF RECEIPT (SYSTEM-GENERATED) text displayed:
If transaction has no associated Partnership memos, reads "Pres. Nominating Convention Account JF Memo: XX (Partnership attributions do not require itemization)". Otherwise, reads "Pres. Nominating Convention Account JF Memo: XX (See Partnership Attribution(s) below)"

Add text field contains:

Pres. Nominating Convention Account JF Memo:  (Partnership attributions do not require itemization)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/32d4a60f-c394-4acb-a0f7-884aa1adb18b)

Verify Tier 3 link for "Partnership Individual" under "Save & Add Memo" a dead link until transaction is developed. 

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/896d8ae9-18ad-46e1-94dd-6f4fc198a5a5)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ad416893-964a-4489-85fa-2341faa89783)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3ef74bd3-6747-440c-8138-e6638f58c444)

The "Transaction ID" and "Associated with" for these transactions are not displayed and referenced correctly as shown in screenshot below.   The "Associated with" is missing.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d77d0cb9-ff6d-4f28-88b3-7259c7fb610d)

@mjtravers @MitchellTCG Returned to In-Progress for "Associated with" transaction fix for memo to transaction.

**Comment by mjtravers** [comment]
Fix for missing Associated With ids on transaction list tables made. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Retested this ticket after fixes. This Tier 3 transaction is a dead link as denoted by DEV in QA notes.  (Ticket #468 and #469 show Tier 3 "Partnership Receipt transaction implemented.)

Prerequisite a "Joint Fundraising Transfer - National Party Pres. Nominating Convention Account" transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d41037f1-5c80-46ab-9f88-9142514a811e)

Select the + Save & add memo button. Verify dropdown list is displayed. Then select "Partnership Receipt" from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/d49e5729-4680-4fa3-b538-405b908c1b1e)

Verify "Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo" page is displayed and contact type is "Organization" only

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/85b7c560-a7fb-499a-b761-7ad1a86abe94)

Verified text - PURPOSE OF RECEIPT (SYSTEM-GENERATED) text displayed:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6f3fb239-e032-4182-8889-3340563c5744)

Verify Tier 3 link for "Partnership Individual" under "Save & Add Memo" is displayed (Not selectable for this ticket, as this is a dead link).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/90255316-c740-4c94-b9b5-6df34baa2f97)

Tier 3 memo "Partnership Individual Recount/Legal Proceedings Account JF Transfer Memo" is a DEAD link for this ticket.

Verified the "Transaction ID" and "Associated with" for tier 2 is displayed and referenced correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b4d953fb-03ef-4d77-ae59-b93fe4e36651)

QA Review Completed. Fixes have been implemented and Pass. Moved to Stage Ready.
