### ISSUE TITLE
Allow user to enter Partnership Receipt Headquarters Buildings Account JF Transfer Memo on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#505]
Business Reason 
 
As a Committee Administrator, I will be able to enter a **”Partnership Receipt Headquarters Buildings Account JF Transfer Memo”** sub-transaction under a **”Joint Fundraising Transfer - National Party Headquarters Buildings Account”**  on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a Tier 2 transaction that will be associated with a Tier 1 t transaction.

 Acceptance Criteria 
 
**Given** I am a Committee Administrator editing an open Form 3X report
**And** I am editing a Joint Fundraising Transfer - National Party Headquarters Buildings Account on an open report  
**Then** I will have the option to enter the following sub-transaction: 
- Partnership Receipt Headquarters Buildings Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (Read-only, includes LOOKUP)
-- Organization 
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required, system checked and read-only)
-	**AMOUNT** (Required, can be negative)
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of all contributions that are:
--- From the person (ENTITY) and within "National Party Headquarters Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_HEADQUARTERS_ACCOUNT")_
--- _from_ January 1 of report year _to_ the Contribution Date* of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**PURPOSE OF RECEIPT** (Read-only, system generated)
-- If transaction has no associated Partnership memos, reads “Headquarters Buildings Account JF Memo: XX (Partnership attributions do not require itemization)". 
--If transaction has associated Partnership memos, reads “Headquarters Buildings Account JF Memo: XX (See Partnership Attribution(s) below)"
--and XX is auto-populated with name of committee entered in Tier 1 transaction JF_TRAN COL SEQ 8.
**-- Note: If the Purpose of Receipt surpasses the 100 character limit, then the system will truncate the committee name (XX text) and end it with "..." so that everything in the parentheses can fit.**
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Save & add memo _(Note that this is a transaction with a possible tier 3 transaction)._
-- Group Name: Joint Fundraising Transfer – Headquarters Buildings; Memo name list: Individual, Party, PAC, Tribal, Partnership
-- Group Name: Partnership Receipt Headquarters Buildings Account JF Transfer; Memo name list: Partnership Individual

- Save 
- Edit 

**And if** the Aggregate amount is >= $200.01 or negative,
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file on line SA17.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

 QA Note 

Tier 3 is live for this ticket (#504 was the dead link only)

 Dev Note 

- BACK REFERENCE TRAN ID NUMBER (COL_SEQ_5) must populate with Tran ID of the parent transaction. This is required.
- BACK REFERENCE SCHED NAME (COL_SEQ_6) must populate with Form Type field of the parent transaction. This is required.
- [x] Update schema to match [Spec Updates spreadsheet tab here]( https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=840306522)

 Wireframe 

![505 - Partnership Receipt Headquarters Buildings Account JF Transfer Memo.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/669e1b73-6e5c-49b0-8ed4-f58c53cae4fc)

# + Save & add more Dropdown 
#
![505 - Partnership Receipt Headquarters Buildings Account JF Transfer Memo Dropdown.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/53d11cc6-c81d-4953-98a6-1667248e53c0)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Updated

**Comment by MitchellTCG** [comment]
Wires updated per our conversation 
@AureliaKhorsand

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Prerequisite a "Joint Fundraising Transfer - National Party Headquarters Buildings Account" transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ebb5b3de-4942-4084-b2cb-8c5325b05485)

Select the + Save & add memo button. Verify dropdown list is displayed. Then select "Partnership Receipt" from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/72fe346e-3c58-4b14-95de-b2e1c6bdd466)

Verify "Partnership Receipt Headquarters Buildings Account JF Transfer Memo" page is displayed and contact type is "Organization" only

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/429f8c18-fb9d-483d-bbde-94aa7dd39fc9)

Verified text - PURPOSE OF RECEIPT (SYSTEM-GENERATED) text displayed:
If transaction has no associated Partnership memos, reads "Pres. Nominating Convention Account JF Memo: XX (Partnership attributions do not require itemization)". Otherwise, reads "Pres. Nominating Convention Account JF Memo: XX (See Partnership Attribution(s) below)"

Add text field contains:

Headquarters Buildings Account JF Memo: Nat... (Partnership attributions do not require itemization)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/3cd296bb-ade2-4f8e-9d64-f22c9d7ef034)

Verify Tier 3 link for "Partnership Individual" under "Save & Add Memo" a dead link until transaction is developed.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e39beb1e-3543-4fe0-b798-80d5b647aa85)

Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a9815e20-6cec-4017-9f77-c585bbd7f0dc)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bc04cafa-2c3e-4878-8946-ae99c33d329c)

The "Transaction ID" and "Associated with" for these transactions are not displayed and referenced correctly as shown in screenshot below. The "Associated with" is missing.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dc7307d8-5f8e-4757-ad04-aa05c310cc57)

@mjtravers @MitchellTCG Returned to In-Progress for "Associated with" transaction fix for memo to transaction.

**Comment by mjtravers** [comment]
Fix for missing Associated With ids on transaction list tables made. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
Retested this ticket after fixes. This Tier 3 transaction is live and developed #505.

Prerequisite a "Joint Fundraising Transfer - National Party Headquarters Buildings Account" transaction to be created, saved in the "Transactions" table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0f2a3e01-c9e4-4f14-a2c1-fd7da0c9dcb0)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/5a7c3df6-7dd4-45f4-9208-e9434672c36f)

Select the + Save & add memo button. Verify dropdown list is displayed. Then select "Partnership Receipt" from the dropdown.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7025b36c-5734-4da1-8835-206199c7b4e7)

Verify "Partnership Receipt Headquarters Buildings Account JF Transfer Memo" page is displayed and contact type is "Organization" only

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e2b3a162-0a3a-4ea2-b400-ac28868ebffe)

Verified text - PURPOSE OF RECEIPT (SYSTEM-GENERATED) text displayed:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/ed43b5b7-35a1-4ba8-8cae-21edbb502a5d)

Verify Tier 3 link for "Partnership Individual" under "Save & Add Memo" displayed.  (Tier 3 will be tested in #507)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8388e91b-25c2-48a2-a9e4-7709b9abd23d)

Verified the "Transaction ID" and "Associated with" for tier 2 is displayed and referenced correctly.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7c01e611-63dd-4999-af47-da4ef83beb08)

QA Review Completed. Fixes have been implemented and Pass. Moved to Stage Ready.
