### ISSUE TITLE
Allow user to enter Tribal National Party Headquarters Buildings Account JF Transfer Memo on Schedule A (Group D)

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#609]
Business Reason 
 

As a Committee Administrator, I will be able to enter a **’Tribal National Party Headquarters Buildings Account JF Transfer Memo ‘** sub-transaction under **"Joint Fundraising Transfer - National Party Headquarters Buildings Account"** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

NOTE: This is a "child" transaction that will be associated with a parent transaction.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator
**And** I am editing a Joint Fundraising Transfer - National Party Headquarters Buildings Account transaction on an open report
**Then** I will have the _option_ to enter the following sub-transaction:
- Tribal National Party Headquarters Buildings Account JF Transfer Memo

**And** I will be required to enter the following information (unless otherwise noted):

---

# Contact 
#
-	**CONTACT TYPE** (required, read-only, **INCLUDES LOOKUP**)
-- Organization Only
-	**ORGANIZATION NAME** (Required)

# Address 
#
-	**STREET ADDRESS** (Required)
-	**APARTMENT, SUITE, ETC.** (Optional)
-	**CITY** (Required)
-	**STATE/PROVINCE** (Required)
-	**ZIP/POSTAL CODE** (Required)

# Receipt Information 
#
-	**DATE RECEIVED** (Required)
-	**MEMO ITEM** (Required)
-- This will be automatically checked and the user CANNOT change it.
-	**AMOUNT** (Required)
**Note:** AMOUNT can contain a negative value.
-	**AGGREGATE** (Required)
-- Amount Displayed will be the total of contributions that are:
--- From the person (ENTITY) and within "National Party Headquarters Account" _(Dev/QA Note: Aggregation Group is "NATIONAL_PARTY_HEADQUARTERS_ACCOUNT")_
--- from January 1 of report year to the Contribution Date of the transaction. 
--- *If there are two transactions with the same Contribution Date for the contributor, use date/time stamp transaction was created.

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only, system-generated)
Multi-line textbox that MUST SAY “Headquarters Buildings Account JF Memo: XX” where XX is auto-populated with the name of the committee entered in parent transaction JF_TRAN COL SEQ 8
-	**NOTE OR MEMO TEXT** (Optional)

---
**Then** I will be able to:
- Cancel
- Save & add another “Tribal National Party Headquarters Buildings Account JF Transfer Memo" associated to the same "parent"
- Back to Joint Fundraising Transfer - National Party Headquarters Buildings Account
- Save & view all transactions [will go to "Manage your transactions" Table]
- Edit as needed

**And if** the Aggregate amount is >= $200.01, 
**Then** the transaction will be itemized upon saving and saved with it's own line item on the *.fec file.

**If** the Aggregate amount is <= $200,
**Then** the transaction will be unitemized upon saving and saved  _without_ it's own line item on the *.fec file.

- [x] Update schema to match [Spec Updates spreadsheet tab here](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=565590404)

### QA Notes ### 
  Dev Note 
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @mary-tcg Needs updated wireframe.

**Comment by mjtravers** [comment]
Passes code review. Ready for QA.

**Comment by WiseQA** [comment]
QA review verified Tribal National Party Headquarters Buildings Account JF Transfer Memo is listed in the dropdown list.

![image](https://user-images.githubusercontent.com/96139912/210827764-2b82ddda-e588-4186-a70b-882c5613f97c.png)

Verify Confirm popup window is displayed

![image](https://user-images.githubusercontent.com/96139912/210828321-add9382c-9ecc-4e7a-91e0-bc018a0f168a.png)

Verified Tribal National Party Headquarters Buildings Account JF Transfer Memo page is displayed.

![image](https://user-images.githubusercontent.com/96139912/210828705-323aa40a-ccff-460f-b0d2-fa360c33889e.png)

![image](https://user-images.githubusercontent.com/96139912/210829002-33b3b985-b0b5-459d-b9ed-825427598aa3.png)

Verify Tribal National Party Headquarters Buildings Account JF Transfer Memo is listed in Transactions table as a "Child" to the original Joint Fundraising Transfer transaction.  And Verified Transactions table is updated, and transaction is itemized – Aggregate amount is >200.01.

![image](https://user-images.githubusercontent.com/96139912/210829821-bd1b5430-2a74-42df-aed2-2a8f80f95697.png)

Verified Transactions table is updated, and transaction is unitemized – Aggregate amount is <200.00.

![image](https://user-images.githubusercontent.com/96139912/210830805-cdb727c7-c977-4f0b-84f4-4cc7060f6dc4.png)

Returned to In-Progress "Back to Joint Fundraising Transfer" button is missing, showing Cancel instead of correct button.

![image](https://user-images.githubusercontent.com/96139912/210831596-7188ddb3-1ec5-49d7-be22-6ed8c161b52d.png)

![image](https://user-images.githubusercontent.com/96139912/210831912-3130cc7c-3480-401b-9f8e-230e9a45ff84.png)

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG See below another memo screenshot showing buttons.  The PAC National Party Pres. Nominating Convention Account JF Transfer Memo showing the buttons as denoted in Acceptance Criteria.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/46205950-cfa1-4ab6-b224-ac5118a4ed3b)

Below another screenshot showing buttons on memo's.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/97962ffb-8e9a-41f7-999f-874fe3ab1eca)

**Comment by mjtravers** [comment]
Buttons updated to match other JF Transfer Memo screens and the screenshots above. Sending to CR.

**Comment by mjtravers** [comment]
Passes CR with the updated buttons for all 3 JF Transfer Memo screens for this group. Sending to QA.

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG Back to Joint Fundraising Transfer button not displaying still show "Cancel".  Cleared cache, cookies, restarted DEV and still get same screen as displayed below.  Sent back to In-Progress.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/82ee30ce-2e01-401c-a93e-dc9dee3ae1cc)

**Comment by WiseQA** [comment]
The memo's needing updated are under 
Joint Fundraising Transfer - National Party Headquarters Buildings Account
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/cc475dbc-c259-46d7-b7ed-3db0166fd9ed)

With exception of partnership which has not been developed.

**Comment by mjtravers** [comment]
The code had not deployed to DEV as I had thought. I redeployed and verified the change. Please take a look again.

**Comment by WiseQA** [comment]
Verified "Back to Joint Fundraising Transfer" button is displaying and the "Save & view all transactions" button.   Cancel button has been removed from this page.


![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2f794b15-ddcb-45bd-aabd-ee7f63f3d89d)

After further testing the when adding a memo and select "Save and add another memo" button I get the following error.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1fec4ec0-42d5-405b-8532-7767a8643790)

@mjtravers returning to In-Progress for bug fix, per our conversation with @dheitzer and @MitchellTCG

**Comment by mjtravers** [comment]
The problem with the error when saving a "memo" with JF Transfer has been captured in ticket [api#320](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/320). The error will be resolved in that ticket and is now outside the scope of this ticket. Moving ticket back to QA.

**Comment by WiseQA** [comment]
@mjtravers - Bug created for "When adding a memo and select "Save and add another memo" button" receive error.  This bug impacts several tickets in the pipeline.

https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/320

This tickets returned to QA Review as this ticket passes functionality as written.  See QA review above verifying functionality.

QA Review Complete.   Moved to Stage Ready.
