### ISSUE TITLE
Allow user to delete a contact ONLY if no associated transactions

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#69]
Business Reason 
 

As a Committee Administrator, I will be able to delete a contact so that I can maintain an up-to-date contact list without any duplicates or contacts created in error.

 Acceptance Criteria 
 

**If** I am a Committee Administrator
**When** I go to Contact Management and/or view a contact
**Then** I will be able to delete that contact _ONLY IF_ there are no transactions associated with it
**And** if there are transactions associated with the contact, the system will inform the user that they cannot delete the contact due to associated transactions.

**Dev Tasks:**
1. refactor old code
2. unit tests
3. documentation
4. logging in the back-end
5. accessible in the UI

![Delete Contacts - Tooltip.png](https://images.zenhubusercontent.com/621cecaf32b9700fedb7b3e6/76fff808-623a-4f56-b64f-a999848dccd7)

### QA Notes ### 
 For this ticket, deleted contacts are permanently deleted, and the user cannot restore them from the front-end. (In the future, deleted contacts will be recoverable. See #88)

Confirmed that there is NO confirmation pop-up.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Question for FEC: Should these be recoverable? What happens if the contact is associated with a transaction? Should the user still be allowed to delete it?

**Comment by lbeaufort** [comment]
> Question for FEC: Should these be recoverable? What happens if the contact is associated with a transaction? Should the user still be allowed to delete it?

@AureliaKhorsand I would ultimately defer to usability research on this, but because contacts hold valuable contact information, it would be ideal to make them recoverable. Committees should have additional records, but if a contact has 20 years of contribution data (or 10 different addresses over time) associated with it, it seems more user friendly to make them recoverable.

**Comment by AureliaKhorsand** [comment]
DEV NOTE: There is functionality in the system to delete, but it's unclear on if it's working or not. Need to ensure users can view all transactions for a contact before this can be fully tested.

**Comment by MitchellTCG** [comment]
@mary-tcg 
Please create a wireframe for this scenario. In the upper left hand portion of "Redesign Sketch Pad - Take 4" (XD File), you will find Artboard titled "Delete Contact". Please remove the Edit icon and three dot actions icon. Replace them with a trash can (found to the right). Make at least two rows have a trash can with only 30% opacity. Above one of the 30% opacity trash cans, please add a tooltip that explains to the user this contact can not be deleted because it is associated with a transaction. Please have this completed by the UX meeting tomorrow. Ping me if you have any questions.

**Comment by mary-tcg** [comment]
@AureliaKhorsand wireframe updated

**Comment by dheitzer** [comment]
Spoke with @MitchellTCG regarding this ticket  - putting this back in ASA for now.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified a contact can be deleted from the Manage Contacts table if there are no associated transactions to that contact.  Select "Regression Add Contact Edit" from the Manage Contacts table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6347317a-cc03-45f5-a412-a7fc9ee0f389)

Verify Confirm popup appears "Are you sure you want to delete this item" (No or Yes).   Select "Yes".

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/dc201f10-a177-4c20-9daf-1dada63313f4)

Verify contact selected to delete , "Regression Add Contact Edit", is no longer displayed or active in the Manage Contacts table.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/1c0e93a5-d341-437c-a237-e181992b17a7)

QA Review Completed.   Moved to Stage Ready.
