### ISSUE TITLE
Setup nightly e2e Cypress process on CircleCI

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#761]
The Cypress end-to-end testing needs to generate a report nightly using CircleCI resources.

**Tasks**
1. Set up a CircleCI scheduled pipeline (https://circleci.com/blog/using-scheduled-pipelines/) that run the e2e tests and reports any errors found during the run
2. Set up CircleCI Notifications (https://circleci.com/docs/notifications/) to send the e2e test report to the fecfile-alerts Slack channel
3. Be sure to run in --headless mode when on CircleCI

**Acceptance Criteria**
A Cypress e2e report is posted to fecfile-alerts Slack channel automatically each evening.

**QA Notes**
There are issues tracking down the admin of the Slack channel we want to post the reports to so we've broken out that part of the ticket into a follow on ticket [#794](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/794).
For this ticket, a visual verification of the report results running on CircleCI are listed in the comments.
### QA Notes ### 
 **Tasks**
1. Set up a CircleCI scheduled pipeline (https://circleci.com/blog/using-scheduled-pipelines/) that run the e2e tests and reports any errors found during the run
2. Set up CircleCI Notifications (https://circleci.com/docs/notifications/) to send the e2e test report to the fecfile-alerts Slack channel
3. Be sure to run in --headless mode when on CircleCI

**Acceptance Criteria**
A Cypress e2e report is posted to fecfile-alerts Slack channel automatically each evening.

**QA Notes**
There are issues tracking down the admin of the Slack channel we want to post the reports to so we've broken out that part of the ticket into a follow on ticket [#794](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/794).
For this ticket, a visual verification of the report results running on CircleCI are listed in the comments.
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by dheitzer** [comment]
11/30 worked on getting API running in circle using [docker executor](https://circleci.com/docs/building-docker-images/#run-docker-commands-using-the-docker-executor) but ran into an issue due to the lack of filesystem sharing with the remote container.  Plan is to use [Linux VM ](https://circleci.com/docs/using-linuxvm/) option to run the API (initial effort throws network errors with the current compose extra_hosts entry, so may need to workaround this).

**Comment by dheitzer** [comment]
Development complete.  The approach taken was to use the [docker executor](https://circleci.com/docs/building-docker-images/#run-docker-commands-using-the-docker-executor) to spin up containers using Docker Compose for the api/db/worker using Circle's remote docker feature.  This docker is isolated from filesystems/networks for security reasons and it was necessary to create custom e2e images that include the code base for these instances.  Finally, we spin up an additional docker container networked to interact with the api instance to run the e2e tests in and kick them off.  

Current issues: The e2e job is currently kicked off nightly on CircleCI, however our current plan restricts the job to run within 1hr, and fails that time is exceeded.  Because our e2e tests take >1h, the job fails each night.  Additionally, the e2e tests are susceptible to routine 'false postivie' timing failures due to the async nature of the application.  

Because of the current issues, the Slack notifications for the e2e tests have not been enabled at this time.

**Comment by dheitzer** [comment]
To get more e2e tests to run within the 1h CircleCI time limit, we have split out the e2e tests into 5 separate parallel jobs.  Below are screenshot results of each run in a CircleCI nightly run:

cypress/e2e/contacts/**/*
![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/e0edaa53-604c-4d04-8612-6ac2d70921a2) 

cypress/e2e/long-running/**/*
![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/24f3f3da-49a6-4d48-b6ea-a57c01411712)

cypress/e2e/other/**/*
![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/f3d2d586-4d94-438b-bd1c-e271bde4baab)

cypress/e2e/reports/**/*
![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/0d274a08-ebf0-494c-966e-52934ff4ccfb)

cypress/e2e/transactions/**/*
![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/568bf26f-6897-412f-bc45-f7e26183cdd2)

**Comment by WiseQA** [comment]
QA review as an inspection from the screenshot provided above from the DEV team.   

No true QA review completed on this ticket.

Moved to Stage Ready.
