### ISSUE TITLE
Allow user to unaggregate and aggregate a transaction on Schedule A

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-web-app#798]
Business Reason

As a user, I will be able to "unaggregate" (then with the option to aggregate) a transaction so that I can provide additional information for a previous transaction without double-counting the amount for the associated entity.

Acceptance Criteria

***Given*** the user has a Schedule A transaction

  ***When*** the user takes the action to "unaggregate" that transaction

  ***Then*** the transaction amount will _not be included_ in the entity's total aggregation amount.

***And*** the user can re-aggregate the transaction if needed.

DEV notes

*   In *.fec file, there is nothing to indicate that a transaction is aggregated or not. It's just not added in the aggregation for that entity.

Wireframes

1.  Unaggregate/Aggregate in Action Kebab

       ![798 Unaggregate - Select.png]([https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7864492e-50e9-4a2a-b9b8-2a92ffe3f16e](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/7864492e-50e9-4a2a-b9b8-2a92ffe3f16e))

1.  Unaggregate is denoted under the transaction name like Unitemized (previously had a different hex code, is now the default 212121)
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFJyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9883e63e916b68a27e6c598d71733041fa5c24a6/798%20Unaggregate%20-%20Displayed.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFJyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9883e63e916b68a27e6c598d71733041fa5c24a6/798%20Unaggregate%20-%20Displayed.png))

1.  Version showing a transaction both Unaggregated and Unitemized
    [Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFZyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f117850f44080562f3d673cf3ae08894ed531559/798%20Unaggregate%20-%20Unitemize.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFZyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f117850f44080562f3d673cf3ae08894ed531559/798%20Unaggregate%20-%20Unitemize.png))

Version showing drop-down option to aggregate a currently Unaggregated transaction
[Private Zenhub Image]([https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUZzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d9715c8b7318303030e4818e3eec609e26940241/798%20Unaggregate%20-%20Aggregate%20Displayed%20%E2%80%93%201.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUZzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d9715c8b7318303030e4818e3eec609e26940241/798%20Unaggregate%20-%20Aggregate%20Displayed%20%E2%80%93%201.png))

Prototype
[https://images.zenhubusercontent.com/306118986/dfd8c703-78e8-4100-8daf-a2aa73ebacaa/798_unaggregate___prototype.mp4](https://images.zenhubusercontent.com/306118986/dfd8c703-78e8-4100-8daf-a2aa73ebacaa/798_unaggregate___prototype.mp4)

### QA Notes ###
null

### DEV Notes ###
null

### Design ###
- [x] BA/Design Quality Checklist complete

 See full ticket and images here: [FECFILE-886](https://fecgov.atlassian.net/browse/FECFILE-886)

**Comment by AureliaKhorsand** [comment]
See Requirements Session notes from 12/13/22.

Example scenario for Receipts: On a Q1 report, say Person A gives money (receipt), but the committee doesn't have their employer/occupation information. Later on, they get the information for the Q2 report, so they report the receipt again. In order to not be calculated into the Summary totals, it is a memo item. In order to not be double counted against Person A's YTD aggregate, the committee will "unaggregate" the transaction. (Employer/Occupation is the most common example for missing info, but other info can be missing too)

**Comment by JonellaCulmer** [comment]
@AureliaKhorsand For the example you provided, it seems we should steer the individual to an amendment, rather than accommodate for this when it doesn't seem to happen all the often. Especially for something like adding in someone's employer/occupation. 

Are there other examples where this scenario is the only method to resolve this "unaggregation" issue?

cc: @GreggMoreland @MitchellTCG @mary-tcg

**Comment by AureliaKhorsand** [comment]
@JonellaCulmer Correct, FEC would prefer an amended report, but users still do this sometimes since it's technically admissable. If we want to help guide them in that direction, I think that could work too. A better example would be for Independent Expenditures - a user may need to report a disbursement early on a Form 24 and then that same transaction on the following Form 3X, and it will need to be unaggregated to avoid double counting.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Wireframe and Prototype attached

**Comment by AureliaKhorsand** [comment]
@MitchellTCG will the user be able to "Aggregate" an unaggregated transaction the same way? Should the term "unaggregated" show on the transaction entry form anywhere? (I think I saw a screenshot of that somewhere, same as "unitemized". Is the latter even implemented?)

**Comment by mary-tcg** [comment]
@AureliaKhorsand Added aggregation drop-down wireframe per your request

**Comment by mjtravers** [comment]
**QA Note:** The dash showing in the wire frame table for the aggregation amount for unaggregated transactions is being changed to show the total aggregation amount without the value of the unaggregated transaction. See discussion from chat here:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXI0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e1d07284abdb5f7c83ff6cc7df37e277d68baa6a/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified in the "Transactions in the report" page under the "Receipts" section the "Actions" dropdown list displays the option to select "Unaggregate"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVA5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1e89a8740cf5472434ca6f78a8f9352e3982f1ef/image.png)

Verified once selecting the "Unaggregate" option from the "Actions" dropdown list "Unaggregated" is displayed under the "Type" of transaction name.

Verified in the "Transactions in the report" page under the "Receipts" section the "Actions" dropdown list displays the option to select "Aggregate"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWI5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--592abdedafe8d999039b0f3dc1677dbb7eb155aa/image.png)

QA Review Completed.   Moved to Stage Ready.
