### ISSUE TITLE
UI: Update top navigation

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#939]
As the UX lead, i would like nav links in the top nav of the page to be updated

 Acceptance Criteria 

The following NAV links will be spelled out:

# Dashboard 
#

# Reports 
# 

# Transactions 
#

# Contacts 
#

# Tools 
#

The following NAV links will be icons

# Notification 
#
Bell see below

# Profile 
#
Avatar see below

Text
font-family: Karla-bold
font-size: 12px 

Text should have 16px of padding left and right and centered vertically in 80px high nav block
padding-left: 16px
padding-right:16px

All unselected text and icons are:
color: ~#777777~ #5B616B

If selected :
Color: #112E51

On hover the color should be also be:
Color: #112E51

also
4px high block
The width should be 16px to left and right of the 
border-radius: 0 0 2px 2px;

Destinations:
Dashboard -> first page of the app after loggin in

Reports -> Manage all report

Transaction -> Manage all transactions

Contacts -> Manage all contacts

Tools 
    \__  Import
    \__  Export
    \__  Update cash on hand
    \__  FECFile Help

Notifications

Profile
    \__  Account
    \__  Users
    \__  Switch Committees (dead link make Grey #D6D7D9)
    \__  User Profile (dead link make Grey #D6D7D9)
    \__  Log Out

 Wireframe 

![60 - Updated Accouint Info.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d80894f8-42c2-4e3e-b1e3-9060a47c61f0)

![Notification-icon.svg](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2ec12030-b51b-4ef7-b7a6-7558cd82d838)
![Profile-icon.svg](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/37269361-e3d6-40a5-863d-62fac24309ad)

 UA Note 

We will deal with the orange notification number in a separate ticket. UX still needs to figure out what needs to be conveyed to users in the notifications.

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by MitchellTCG** [comment]
@mjtravers @toddlees @dheitzer @Elaine-Krauss-TCG

Please review this ticket and make sure all the info makes sense.

**Comment by Elaine-Krauss-TCG** [comment]
The active page has a 4px tall black bar above its entry on the navbar.  The subtle 2px radius on the bottom of the bar will not work without a massive lift to make it its own self-contained div.  It also does not currently display above the User Profile Icon when you are on one of the pages it links to.  This is because the p-menubar component in PrimeNG does not register a nav-item as active when one of its sub-items' urls match.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/708724f6-57bd-4280-9363-b40d1b0339ff)


Nav items are 80 pixels tall (including all padding) with 16px of padding on the left and right
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/9f9b9c4a-e855-473c-a9a3-5ca4889bafe9)

The font-family, font-size and color of active items
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/f87ff429-16cd-4bb0-ab1d-2fc7099f738c)

The color of inactive items
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/8f81b7c8-ad5c-4907-ab13-9f83d1d0938c)

The color of the requested dead links
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/fdf6d648-37d6-4eca-9d72-8d40163e7b23)

**Comment by Elaine-Krauss-TCG** [comment]
@MitchellTCG 

The chosen font color for inactive pages on the navbar sets off contrast alerts in ANDI.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/f20048ab-3d07-438a-8948-b902d219b230)

**Comment by Elaine-Krauss-TCG** [comment]
The bar displayed over the active nav-item works for pages that are linked to from a drop-down, but this is dependent on a very modern css feature [:has()](https://developer.mozilla.org/en-US/docs/Web/CSS/:has)
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/7600c2ae-dd59-43fa-8904-a60de577640f)

This feature has been added to all major browsers except Firefox, though it is [under active development](https://connect.mozilla.org/t5/discussions/when-is-has-css-selector-going-to-be-fully-implemented-in/td-p/23794) for that browser.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/2900b005-dba5-4983-9569-1eec1126b2dc)

Today's Firefox as well as out-dated browsers will simply not display the bar when you're on a sub-item's page.

**Comment by MitchellTCG** [comment]
@Elaine-Krauss-TCG change the grey from #777777 to #5B616B
this goes from [1:4.48]  to [1:6.23]

**Comment by Elaine-Krauss-TCG** [comment]
The navbar shrinks down much smaller now without the icons disappearing
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/a5336dc7-bdb2-411b-8044-754545b1e4d0)

No more carets either
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/b00296af-79f2-4617-9577-24f452d5550e)

**Comment by mjtravers** [comment]
A few items from CR to address:

- [x] Make the sub title of the Committee Account banner not wrap
- [x] Have the horizontal select bar across the REPORTS menu item be visible as the user drills into a report's sub-pages (It now shows over Transactions when at /transactions urls)
- [x] When the left nav bar is displayed, have the top menu items have one call across the top rather than the current col-4 and col-8 setup
- [x] Remove carrots from TOOLS and PERSONNEL navbar items

Sending back to In Progress

**Comment by Elaine-Krauss-TCG** [comment]
When on transaction-related pages, the black bar shows over "Transactions."  Making it show over "Reports" instead would actually be a big lift.  The problem is that the url starts with "/transactions" instead of "/reports" and any fix for that would get very hacky very fast.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/958a5d1c-f364-475d-9987-f76d8dd86c24)

It shows the black bar over "Reports" for all other report related page.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/7756da67-2fbd-43b6-b7a4-ddc59acea086)

**Comment by mjtravers** [comment]
We can look into rearranging the router URLs so that the "Reports" menu item keeps the top horizontal bar when managing report transactions. Let's review together and see if we can come up with a plan that isn't too disruptive. Sending back to In Progress.

**Comment by mjtravers** [comment]
Routing has been fixed so that when viewing report transactions the horizontal bar stays above the Reports menu item. Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified the dashboard displays for Notification a Bell and for Profile an Avatar (as denoted above).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/61d4170f-34f5-45ff-9df0-8ebbb09f27b4)

Verified top horizontal bar is displayed when selecting DASHBOARD:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/eeff89de-ec7d-408e-b5d2-136a494976aa)

Verified top horizontal bar is displayed when selecting REPORTS:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/10e91313-a1fd-4b03-a8f3-8e165bc3e931)

Verified top horizontal bar is displayed when selecting TRANSACTIONS:   **THIS FAILS**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/569a8963-cd54-4bed-a1b8-ffff2e777035)

Verified top horizontal bar is displayed when selecting CONTACTS:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/025ade06-c898-421d-9042-c79a26a475dd)

**@MitchellTCG @mjtravers When selecting TOOLS from the navigation bar, is there suppose to be a top horizontal bar displayed ?  Need clarification on this.**

@mjtravers @MitchellTCG returning to In-Progress for fix of the top horizontal bar above TRANSACTIONS.

Verified top horizontal bar is displayed when selecting TRANSACTIONS:   **THIS FAILS**

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/569a8963-cd54-4bed-a1b8-ffff2e777035)

**Comment by mjtravers** [comment]
@WiseQA There are no web pages for Tools yet so the horizontal bar will never be shown for that navigation selection. Same for the Transactions navigation selection. The only transaction pages we have are in reports so the horizontal bar will show over the Reports menu selection. I believe there is a future requirement for a list of all transactions across reports that this is the page that will be displayed when the Transaction navigation selection is clicked. @MitchellTCG can confirm this.

**Comment by WiseQA** [comment]
@mjtravers @MitchellTCG  okay I didn't see that in the ticket about the top horizontal bar only applies to Dashboard, Reports and Contacts only then.  Tools I figured as much no top horizontal bar just double checking.   If this is correct then move ticket back to QA Review.   Thanks !

**Comment by mjtravers** [comment]
As confirmed at the meeting after this morning's DSU, there are only 4 navigation menu items that will have content pages and the horizontal bar above them: DASHBOARD, REPORTS, CONTACTS, and the profile icon. Sending ticket to QA.

**Comment by WiseQA** [comment]
QA review reverified the 4 navigation menu items showing the top horizontal bar are the DASHBOARD, REPORTS, CONTACTS, and under the profile icon (Account and Users).

QA Review Completed. Move to Stage Ready after Sprint 26 review 22 June 2023.
